- classes/OccurrenceListManager.php
- classes/OccurrenceManager.php
- classes/SearchManager.php
Hi, Ed,
As a reality check there are 2 commits here contain my fixes: bdc2500 and b1faae4.  Between the 2 of them, only 3 files were changed:
classes
SearchManager.php
OccurrenceManager.php
OccurrenceListManager.php
Tom
> Fixes for Any Name synonym handling, common name apostrophe handling, and empty results.

- classes/SpecUploadBase.php
- collections/admin/specupload.php
- collections/tools/idigbio_media_adjustments.php
- Added increased import restrictions to avoid continual import of blank records.
> Specimen Import adjustments

- checklists/checklist.php
- checklists/clsppeditor.php
- classes/ChecklistAdmin.php
- classes/ChecklistLoaderManager.php
- classes/ChecklistManager.php
- classes/ChecklistVoucherManager.php
- classes/ImageLocalProcessor.php
- classes/ImageProcessor.php
- classes/OccurrenceMaintenance.php
- classes/RareSpeciesManager.php
- classes/SpecUploadBase.php
- collections/misc/rarespecies.php
- Refactored algorithm and SQL to more efficiently tag specimens for protection
- Add controls to global rare species page that show count of specimens pending project and button to protect specimens
- Add controls to rare species state managment page that show count of specimens pending project and button to protect specimens
- Add protection counts reporting to upload controls
> Sensitive Species Protection Development

- classes/OccurrenceListManager.php
- collections/list.php
- Added message stating when localities are protect, even when user if logged in and authorized to  view these details. This is needed to avoid continuous confusion.
> Occurrence Locality Protection

- classes/PermissionsManager.php
- collections/misc/collpermissions.php
- Limited permissions removal to only only records that were originally assigned by logged in user
> Personal Observation Management Development

- classes/TaxonomyCleaner.php
- classes/TaxonomyHarvester.php
- Finishing syncing cleaning tool to targetted kingdoms to avoid loading and linking homonyms from other kingdoms
- Misc bugs fixes
> Taxonomy Cleaning tool development

- classes/APIOccurEditor.php
- classes/OccurrenceEditorDeterminations.php
- classes/TaxonomyHarvester.php
- Adjustments to Catalog of Life harvesting algorithm to improve return of infraspecific taxon searches
- Mics spelling adjustments
> Taxonomy Cleaning development

- classes/TaxonProfile.php
- taxa/index.php
- Deactivate Google static map display for genera displays. This is needed to reduce the cost of Googles new pricing plans. In truth, the static thumbnails are not very useful.
- Minor adjustments to layout
> Taxon Profile page adjustments

- checklists/checklist.php
- classes/ProfileManager.php
- classes/SpecUploadDwca.php
- imagelib/imgdetails.php
- projects/index.php
- taxa/index.php
- Further temporary walk back of Google static thumbnail displays until Google account issue is worked
> Google Map Adjustments

- classes/KeyMassUpdate.php
- Bug fix that was restricting display of all taxa within editor
- Bug fix that  interfered with full alphabetical display of taxa list
> Identification Key Editor development

- classes/PermissionsManager.php
- classes/TaxonomyHarvester.php
- Minor bug that was skipping some taxa that were several layer within the JSON return
> Taxonomic CoL harvester update

- classes/OccurrenceMapManager.php
- collections/map/kmlhandler.php
- Bug fix for KML output function within dynamic map page
> Occurrence Map function development

- classes/OccurrenceTaxaManager.php
- Improvement on family level search algorithm to reduce server load
> Occurrence Search Modifications

- collections/editor/occurrencetabledisplay.php
- config/symbbase.php
- css/base.css
- css/main_template.css
- footer_template.php
- header_template.php
- header_template_multi_lang.php
- themes/liquid/css/main.css
- themes/liquid/header.php
- themes/static/css/main.css
- themes/static/footer.php
- themes/static/header.php
>  Misc Layout adjustments

- classes/OccurrenceEditorDeterminations.php
- classes/OccurrenceEditorManager.php
- collections/editor/occurrenceeditor.php
- Added explicit check if crowdsource record is open or reviewedd and closed
to edits. Mid-Atlantic crowdsource editors were able to edit their records after being closed.
- Tightened security checks to verify editing permissions
> Occurrence Editor adjustments

- classes/OccurrenceEditorManager.php
- collections/editor/occurrenceeditor.php
- collections/specprocessor/standalone_scripts/media_scripts.php
Minor bug inhibiting display of exsiccati details within editor form
> Occurrence Editor bug

- collections/specprocessor/standalone_scripts/custom_voucher_linker.php
- collections/specprocessor/standalone_scripts/idigbio_media_adjustments.php
- collections/specprocessor/standalone_scripts/media_scripts.php
- Finish debugging media maintenance scripts
- Minor adjustments to script to accommodate new script location
> Standalone script development

- classes/OccurrenceGeoLocate.php
- classes/OccurrenceUtilities.php
- classes/SpecUploadBase.php
- Add ability to import coordinate error formats with numeric value and units imported as separate values
- Improved automapping functions
- Misc GeoLocate error
> Specimen Upload Development

- classes/OccurrenceEditorManager.php
- Improvements within batch field update functions
> Occurrence Editor Adjustment

- classes/KeyCharDeficitManager.php
- classes/KeyDataManager.php
- classes/KeyManager.php
- classes/KeyMassUpdate.php
- classes/OccurrenceTaxaManager.php
- ident/admin/headingadmin.php
- ident/tools/chardeficit.php
- Expand taxa search to be more greedy based on infra-specific taxa
- Finish integrating parent/child checklist relationships into identification key module
- Bug fix that intefered with trait inheritance in certain taxonomic relationship definitions.
> Occurrence Search and ID Key developments

- checklists/checklist.php
- checklists/checklistadminchildren.php
- checklists/checklistadminmeta.php
- classes/ChecklistAdmin.php
- classes/ChecklistManager.php
- content/lang/checklists/checklist.en.php
- content/lang/checklists/checklist.es.php
- Added initial framework to support a species exclusion checklist for Bungartz
- Added increased clarity to user concerning relationship between parent and child checklists
- Expand multiple language support within checklist module
> Checklist Devlopments

- classes/OccurrenceEditorManager.php
- classes/OccurrenceUtilities.php
- Fix of bug that was interfering with display of all records within full table view
- Minor bug displaying warning within occurrence import tool
> Occurrence Editor bugs

- classes/GamesManager.php
- games/ootd/index.php
- games/ootd/readme.txt
- Modify code to randomize image naming in order to resolve image caching issue displaying images from previous days
- Misc code updates
> Game Module Development

- checklists/tools/mappolyaid.php
- js/symb/wktpolygontools.js
- Add reformatting tool to covert coordinate tuple polygons used within NEON KLM files to wktfootprint polygons that can be queried against MySQL spatial indexes
- Fixed bug that was adding duplicate trailing points after each open, reformat, and save
- Fix bug that failed to reformat strings with trailing whitespace
- Improved extent of reformatting tool
> Polygon Management tool development

- classes/ChecklistAdmin.php
- protection against checklist type getting switched to NULL during a checklist metadata update
> Checklist Management bug

- classes/ImageLibraryManager.php
- classes/OccurrenceTaxaManager.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Improved security to protect against user submitting multiple wildcard terms to hack return of full datasets beyond the portal's ability to return hindering db preformance.
> Taxon Search Protection

- classes/SpecUploadBase.php
- classes/SpecUploadDwca.php
- Fixed bug associated with new ability to filter incoming DwC-A import files based on multiple OR terms matching fields within input data file
> DwC-A Import Development

- classes/SpecUploadDwca.php
- Additional bug fix to previous code submit
> DwC-A Import Devlopment

- classes/ImageLocalProcessor.php
- classes/ImageProcessor.php
- classes/SpecUploadBase.php
- classes/TaxonomyCleaner.php
- classes/TaxonomyUpload.php
- classes/TaxonomyUtilities.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- taxa/taxonomy/batchloader.php
- Added ability to use full name taxon rank terms in place of rankids, with rankids obtained from taxonunit table defintions
- Fixed bug that was inserting genera ranks twice in certain conditions
- Extended automating function to greater number of common terms
> Taxonomic Thesaurus upload development

- taxa/index.php
- Minor adjustment to display of editing symbol to make it more accessable
> TaxonProfile adjustment

- checklists/checklistadmin.php
- classes/ChecklistAdmin.php
- classes/InventoryProjectManager.php
- classes/OccurrenceDataset.php
- classes/PermissionsManager.php
- Fixed bug that interferred with removal of permissions in certain situations
- Improved access and display of name of person assigning permission
- Misc code improvements
> Permission Management adjustments

- collections/editor/includes/queryform.php
- Removed genus and specific epithet from search form in preference for compound searches on scientific name
> Occurrence Editor Modification

- classes/SpecUploadBase.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Added support for import of additional Audobon Core image terms
> Occurrence Import Modifications

- classes/TaxonomyUtilities.php
- Incorrect method used to close a database connection within a function that is declared as static
- Improved protection against SQL injection
> Taxonomic Utilities bug

- classes/TaxonomyUtilities.php
> Taxonomy Utilities bug

- collections/editor/includes/config/occureditorcrowdsource.css
- collections/editor/occurrenceeditor.php
- css/occureditor.css
- Changed locality text input field into a textarea element
- Improved standardization of the display of controls and image icons by migrating selected styling attributes into css files
- Minor adjustments to layout of crowdsourcing editor
> Occurrence Editor Development

- collections/editor/includes/queryform.php
- Administrators were unable to access and edit all records across a Personal Occurrence dataset
> Minor Occurrence Editor bug

- classes/TaxonomyHarvester.php
- Fixed bug that was regesting the results from WoRMS for each parent taxon up to kingdom even if name was already entered into database. This was not only ineffienct, but also put a heavey load on WoRMS API.
- Extended ability to capture and store source of new name added to database
> Taxonomic Name Harvested development

- imagelib/search.php
> Image Search bug

- classes/TaxonProfile.php
> Minor Taxon Profile bug

- checklists/checklistadminmeta.php
- classes/ChecklistAdmin.php
- content/lang/checklists/checklistadmin.en.php
- content/lang/checklists/checklistadmin.es.php
- Add Display Synonyms to default options
> Checklist Module Development

- checklists/checklistadminmeta.php
- classes/ChecklistAdmin.php
- Fix bug that was interferring with editing checklist metadata after a list is created
- Added the ability to change a checklist type to or from a checklist exclusion list after the list is created
- Misc adjustments
> Checklist Manager adjustments

- classes/ImageProcessor.php
- classes/OccurrenceManager.php
- collections/datasets/datapublisher.php
- collections/editor/dupesearch.php
- Adjusted occurrences merge options so that data is merged into secondary specimen that is not the subject
- Other misc edits
> Occurrence Merge Function adjustment

- classes/OccurrenceManager.php
- classes/OccurrenceTaxaManager.php
- Fix bug that was failing to return specimens IDed only to family when searching by family
- Improve searching by year/month and date ranges
> Occurrence Search adjustments

- classes/TaxonomyUpload.php
- classes/TaxonomyUtilities.php
- taxa/taxonomy/batchloader.php
- Added support to target a specific kingdom
- Isolated and protected cross-kingdom homonym
- Improved support for uploading Animalia
- Fixed various bugs
> Taxonomic Batch Loading Devlopment

- collections/reports/labels.php
- More adjsutments to catch user error and avoid confusion and support emails
> Additional Label Printing adjustments

- checklists/checklistadmin.php
- checklists/checklistadminmeta.php
- checklists/voucheradmin.php
- checklists/voucherreporthandler.php
- classes/ChecklistVoucherAdmin.php
- collections/specprocessor/imageprocessor.php
- content/lang/checklists/voucheradmin.en.php
- content/lang/checklists/voucheradmin.es.php
- Add report option that outputs all related occurrences match using checklists query terms
- Bug fix setting display synonym options
- Only display reports relavent to checklist setup
- Misc code improvements
> Voucher Mangement Development (NYC EcoFlora)

- classes/SpecUpload.php
- classes/SpecUploadBase.php
- classes/SpecUploadDwca.php
- collections/admin/uploadhandler.php
- Misc debug after testing scheduled upload
> Automatic Occurrence Harvest Handler

- classes/OccurrenceUtilities.php
- classes/SpecUploadDwca.php
- Misc bugs and code warning and notices
> Occurrence DwC-A/IPT Upload Module development

- collections/individual/index.php
- collections/specprocessor/imageprocessor.php
- Bug fix due to accidental premature submission of a feature redesign file
> Image Processing Bug

- classes/ChecklistManager.php
- classes/OccurrenceManager.php
- Modification to make sure that correct family is displayed when checklist is filtered through a taxonomic thesaurus
- MInor adjustment to occurrence search
> Checklist Manager bug fix

- checklists/checklist.php
- classes/ChecklistManager.php
- classes/ChecklistVoucherManager.php
- classes/InventoryProjectManager.php
- projects/index.php
- Add ability to replace the main header graphic is a project specific header image. This can be done for checklists or inventroy project
> Checklist Devlopment

- classes/ImageProcessor.php
- classes/OccurrenceIndividualManager.php
- classes/SpecUploadBase.php
- collections/individual/index.php
- Added soruceUrl to occurrence image mapping profiel
> Image Mapping Adjustments

- classes/OccurrenceCrowdSource.php
- collections/specprocessor/crowdsource/review.php
- Add ability for collection managers to change review status
> Crowdsource Modifications

- collections/datasets/datapublisher.php
- collections/misc/collmetadata.php
- Bug fix to hide GBIF publishing controls if option have not yet been activated and configured within portal
> Minor GBIF publishing adjustments

- classes/DwcArchiverCore.php
- classes/OccurrenceTaxaManager.php
- collections/admin/uploadhandler.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- webservices/dwc/dwcapubhandler.php
- Added advanced taxon filtering options to DwC-Archive data export options
> Darwin Core Publishing Dev

- checklists/clsppeditor.php
- checklists/vaconflicts.php
- checklists/vamissingtaxa.php
- checklists/voucheradmin.php
- checklists/voucherreporthandler.php
- classes/ChecklistVoucherAdmin.php
- classes/ChecklistVoucherManager.php
- classes/ChecklistVoucherPensoft.php
- classes/ChecklistVoucherReport.php
- collections/list.php
- collections/rpc/addvoucher.php
- Rework code to better take advantage of class extensions and function sharing
- Bug fix that interferred with voucher linking
> Checklist Voucher Management Refactor

- classes/PluginsManager.php
- Filter out unwanted images from slideshow based on sort order
> Minor Plug-in adjustment

- classes/OccurrenceMapManager.php
- Map failed to render when polygon shape existed within an old format
> Dynamic Map bug

- classes/ChecklistManager.php
- Check validity of coordinates before adding to map
> Simple Occurrene Map bug

- classes/ImageCleaner.php
- imagelib/admin/thumbnailbuilder.php
- Deactivated reset function for more effiecent workflow
> Thumbnail Image Builder

- classes/InventoryProjectManager.php
- projects/index.php
- Only display map if checklists have point coordinates defined
- Display Google thumbnail
> Inventory Project adjustments

- classes/ProfileManager.php
- Trying to improve email reset function to avoid emails from getting caught by SPAN filters
> Password reset issue

- classes/ImageLibraryManager.php
- imagelib/index.php
- imagelib/search.php
- js/symb/imagelib.search.js
- taxa/index.php
- Fix bug for search of image browser name list
- Place text name in search field
- Misc display adjustments
> Image Library Adjustments

- sitemap.php
- Do not display Exsiccati option is exsiccati functions are not not activated in config file
- minor adjustments
> Sitemap adjustments

- collections/listtabledisplay.php
- Modify column order of table view
> Occurrence table display adjustment

- checklists/checklist.php
- classes/TaxonProfile.php
- taxa/index.php
- Bug fix that interferred with opening taxon profile page for upper taxa (e.g. genus, family) from within checklists
- Aviod displaying bad image thumbnails
- Improvement of the efficiency of displaying tchild humbnails for higher taxa
> Taxon Profile adjustments

- checklists/nonvoucheredtab.php
- checklists/vamissingtaxa.php
- checklists/voucheradmin.php
- classes/ChecklistVoucherAdmin.php
- classes/ChecklistVoucherReport.php
- Added option to build list based on voucher specimens in the system without linking vouchers to checklist
> Checklist Development

- classes/TaxonProfile.php
- Bug fix from previous submit
> Taxon Profile adjustment

- classes/OccurrenceAttributes.php
- collections/editor/includes/traittab.php
- collections/editor/rpc/editorTraitHandler.php
- Add source field
- Misc bugs and minor adjustments
- Improve recording of person and time of modifications
> Occurrence Trait Coding Development

- classes/ImageProcessor.php
- collections/specprocessor/imageprocessor.php
- collections/specprocessor/processor.php
- Added option to map images urls to records via otherCatalogNumbers field
> Image Processor Dev

- classes/OccurrenceMaintenance.php
- classes/OmProtectedSpecies.php
- collections/misc/protectedspecies.php
- Further developments to support taxon based occurrence protections
> Taxonomic Protection Development

- classes/OccurrenceListManager.php
- collections/editor/occurrenceeditor.php
- collections/individual/index.php
- collections/list.php
- collections/misc/protectedspecies.php
- Continued developments to support taxon-base species protection for NEON portal development
- Added protection to occurrence record listing
- Added protection for Specimen details page
- Added protection management tools within Occurrence Editor
- Misc adjsutments
> Taxon-base Sensitive Species Protection

- classes/TaxonomyEditorManager.php
- taxa/taxonomy/taxoneditor.php
- taxa/taxonomy/taxonomychildren.php
- Added tab to display children taxa
- Misc adjustments and bugs
> Taxonomy Management Development

- classes/OccurrenceChecklistManager.php
- classes/OccurrenceListManager.php
- collections/list.php
- Further adjustments to NEON taxon security requirements
> Taxon Security Adjustments

- classes/ImageLocalProcessor.php
- Surpress notice to error log when image url is bad
> Image Processor adjustment

- classes/SpecUploadBase.php
- collections/editor/occurrenceeditor.php
- config/symbini_template.php
- js/symb/collections.occureditormain.js
- Added variable with configuration file to control which type of security settings are supported
- Made security protections persistant for imported specimens. This way import settings are not overwritten by local system
> Occurrence Secuirty Development

- classes/OccurrenceSkeletal.php
- collections/editor/skeletalsubmit.php
- js/symb/collections.occurskeletalsubmit.js
- Added Label project to submit form
- Misc adjustments and improvements
> Occurrence Skeletal Submit Dev

- classes/OccurrenceEditReview.php
- misc/usagepolicy_template.php
- Occurrence Review bug: Bug fix that interferred with applying edits that contained double quotes
- Usage policy misspelling
> Misc bugs and misspellings

- classes/OccurrenceEditorManager.php
- Allow wildcard searches on catalog and other catalog numbers
> Occurrence Editor Dev

- checklists/tools/checklistloader.php
- classes/ChecklistLoaderManager.php
- Integrated shared Manage class in order to use the standard character set analysis functions
> Batch checklist loader

- collections/harvestparams.php
- config/symbbase.php
- Force pages to refreshj base.css
- Minor adjustments to occurrence search parameter page
> Minor Adjustments

- webservices/dwc/dwcapubhandler.php
- Added options to web service handler that allows user to include extended Symbiota specific terms within the DwC-A data package
> DwC-A Publishing Dev

- classes/OccurrenceIndividualManager.php
> Occurrence Comment adjustments

- collections/reports/annotationmanager.php
- collections/reports/defaultannotations.php
- collections/reports/defaultannotationsword.php
- Add styling options to annotation printing
> Annotation Printing Adjustments

- collections/datasets/datapublisher.php
- Added link to directions on publishing page
- Modified text to be more current
- Updated links out to other resource
> DwC-A Publishing

- checklists/checklist.php
- classes/ImageShared.php
- classes/OccurrenceEditorImages.php
- classes/TPImageEditorManager.php
- collections/editor/includes/imagetab.php
- collections/editor/occurrenceeditor.php
- config/symbbase.php
- css/base.css
- js/symb/collections.occureditormain.js
- taxa/index.php
- bug fix that inhibited mapping a remote URL of an image
- Add option for user to supply their own image derivatives
- Various adjustments
- Misc style fixes
> Image Upload and Other Adjustments

- classes/ImageShared.php
- bug fix that inhibited mapping a remote URL of an image
- Add option for user to supply their own image derivatives
- Various adjustments
- Misc style fixes
> Image Loading bug

- classes/DwcArchiverCore.php
- webservices/dwc/dwcapubhandler.php
- Minor edits and added documentation on how to use the services
> DWC-A publishing adjustments

- classes/DwcArchiverCore.php
- content/lang/collections/harvestparams.en.php
- content/lang/collections/harvestparams.es.php
- Adjustments to and/or condition priorities
> Occurrence Download Bug

- classes/OccurrenceCollectionProfile.php
- collections/datasets/datapublisher.php
- js/symb/collections.gbifpublisher.js
- Merged verification and save actions into a single button click
- Small improvments to validation
> GBIF Publishing Dev

- classes/ChecklistVoucherAdmin.php
- classes/ChecklistVoucherReport.php
- imagelib/imgdetails.php
> Checklist Voucher bug

- checklists/checklist.php
- classes/ChecklistManager.php
- classes/ChecklistVoucherAdmin.php
- collections/rpc/addvoucher.php
- config/schema-1.0/dev/db_schema_patch_pending_biocache.sql
- content/lang/checklists/checklist.en.php
- content/lang/checklists/checklist.es.php
- js/symb/checklists.checklist.js
- js/symb/checklists.voucheradmin.js
- Bug fix with species addition autocomplete function
- Initial support for morphospecies  definition within checklists
> Checklist Management development

- classes/OccurrenceEditorManager.php
- classes/OccurrenceIndividualManager.php
- collections/editor/includes/paleoinclude.php
- collections/editor/occureditor.php
- collections/editor/occurrenceeditor.php
- collections/individual/index.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- config/symbini_template.php
- css/occureditor.css
- plugins/slideshow/readme.txt
- Adjustments to schema and addition of GTS lookup tables and terms
- create and integrate paleo include into editor
- add term return to editor
- term UPDATE and INSERT processing code
- support for versioning edits
- batch editing tool support for paleo fields
- delete/archive paloe support
- add paleo terms to occurrence pubic display
> Paleo Module Developments

- classes/DwcArchiverCore.php
- collections/download/downloadhandler.php
- collections/specprocessor/exporter.php
- Add processing status and dbpk to custom filter
- Fix bug that limited non-indexed field search
- Add condition limit override option for collection downloads
> Occurrence Download dev

- classes/OccurrenceEditorManager.php
- classes/OccurrenceIndividualManager.php
- Misc modifications to ensure new module will not break portals without paleo module activated
- Misc bug fixes
> Paleo Module debugging

- classes/ImageCleaner.php
- classes/ImageShared.php
- classes/OccurrenceEditorManager.php
- imagelib/admin/thumbnailbuilder.php
- bug fix that was keeping previously failed thumbnails from reprocessing
- Added reset button that allows manager to do a hard reset of thumbnail processing (previously self reset after 24 hours)
- Misc improvements to code efficiency
> Image Maintenance Tools

- collections/datasets/datasetmanager.php
- collections/datasets/occurharvester.php
- collections/editor/batchdeterminations.php
- collections/exsiccati/batchimport.php
- collections/exsiccati/index.php
- collections/reports/annotationmanager.php
- collections/reports/labelmanager.php
- games/flashcards.php
- games/namegame.php
- ident/tools/chardeficit.php
- ident/tools/editor.php
- js/symb/checklists.voucheradmin.js
- js/symb/collections.loans.js
- js/symb/collections.map.index.js
- js/symb/collections.occurskeletalsubmit.js
- js/symb/imagelib.search.js
- js/symb/shared.js
- Various code adjustments to remove dependency on < id="maintable" table> framework so that we can better support flexible portal friendly layouts
> Javascript Adjustments

- collections/cleaning/duplicatesearch.php
- Adjusted form so that duplicate merge bug would still function even when max_input_vars isn't significantly large enough within the server PHP configuration file.
- Set record processing limit to automatically adjust to server's PHP configuration settings
- Added a message to SuperAdmin when max_input_vars variable is set below optimum
> Duplicate Record Merge dug

- classes/DwcArchiverCore.php
- collections/cleaning/duplicatesearch.php
- Collection central contact and email was not be inserted correctly into EML file when DwC-A data was packaged
> Darwin Core Archive bug

- classes/OccurrenceCollectionProfile.php
- js/symb/collections.gbifpublisher.js
- Adjusted code to avoid invalid error messages from GBIF to be stored as dataset key, which resulted in portal errors
> Darwin Core Archive GBIF publishing bug

- css/base.css
Fixes font sizing issue observed by Frank on the Lichen portal and found to be a common thing among portals.
> Merges updates and fixes base.css for font-sizing

- classes/OccurrenceSearchSupport.php
- collections/index.php
- Improved contorl of collections display and sort via  variables within portal's configuration file
> Collection Search Dev

- checklists/clsppeditor.php
- classes/TaxonomyUpload.php
- Reducing number of warning and notices within Apache log files
> Misc minor bug fixes

- classes/OccurrenceCollectionProfile.php
- Added code to get endpoint list, iterate through list to see if there is a match, if there is not a match, then remove old and add new endpoint
- Temporarily deactive code until we get input from gbif IT
> GBIF publication adjustments

- classes/DwcArchiverPublisher.php
- classes/OccurrenceCrowdSource.php
- collections/datasets/datapublisher.php
- collections/misc/collstats.php
- collections/specprocessor/crowdsource/index.php
- imagelib/search.php
- Resolve collection category bug when more than one category is defined
> Collection Category development

- classes/OccurrenceCollectionProfile.php
- Reactivating endpoint remapping code with adjustments
> GBIF DwC-A publishing dev

- classes/OccurrenceManager.php
- classes/OccurrenceSearchSupport.php
- collections/map/index.php
- js/symb/collections.map.index.js
- Refactored collection selection within the search forms to make selections presistant within Map Search and Image Search functions
> Collection Search bug

- classes/OccurrenceEditorManager.php
- collections/editor/occurrencetabledisplay.php
> Occurrence Search bug

- collections/listtabledisplay.php
- content/lang/collections/list.en.php
- content/lang/collections/list.es.php
- Bug interfering with "Copy URL to Clipboard function" within table display
- Occurrence table display bug interfering with proper display of protected localities
- Minor style and translation adjustments
> Occurrence Search Devlopment

- classes/SpecUploadFile.php
-Add support for import of files with accented characters within header row
> Occurrence Upload Support extended

- classes/ImageLibraryManager.php
- SQL optimization needed to reduce load on large databases being hit by search engine indexers
> Image Search Optimization

- collections/editor/imageoccursubmit.php
- config/symbini_template.php
- Added Processing Status field with default value of "unprocessed"
- Added template to symbini configuration file to allow customization of processing status values
> Image Submit Dev

- classes/TaxonomyDisplayManager.php
- taxa/taxonomy/taxonomydisplay.php
- taxa/taxonomy/taxonomydynamicdisplay.php
- Added display of meta data for selected taxonomic thesaurus
- Added a default display of kingdom level taxa for both browse and dynamic display options
- Misc adjustments
> Taxonomic Thesaurus Development

- classes/TaxonomyDisplayManager.php
- taxa/taxonomy/taxonomydisplay.php
- taxa/taxonomy/taxonomydynamicdisplay.php
- Add framework to allow thesuarus display to be limited to only taxa with an occurrence record (NEON portal request)
- Don't display "More Details" button when extended metadata is not supplied
> Taxonomic Thesaurus Management development

- classes/TaxonomyDisplayManager.php
- taxa/taxonomy/taxonomydisplay.php
- taxa/taxonomy/taxonomydynamicdisplay.php
- misc bug fixes and display adjustments
> Taxonomy Metadata

- checklists/checklistadminmeta.php
- classes/ChecklistAdmin.php
- taxa/taxonomy/rpc/getdynamicchildren.php
- taxa/taxonomy/taxonomydisplay.php
- taxa/taxonomy/taxonomydynamicdisplay.php
- Add edit mode control to dynamic
- Add sanatation code
- Provide user option to match on whole words are based on trailing wildcard
> Taxonomy Thesaurus Development

- collections/admin/specupload.php
- collections/specprocessor/imageprocessor.php
- Allow match-on-other-catalog-number variable to carried over from file upload to mapping forms (needed for NEON support)
- Misc spelling fixes
> Specimen Upload Adjustments

- classes/OccurrenceEditorManager.php
- classes/OccurrenceIndividualManager.php
- collections/editor/occurrenceeditor.php
- collections/individual/index.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- config/schema-1.0/utf8/db_schema_patch-1.1.sql
- config/symbini_template.php
- css/occureditor.css
- Moved control of display of custom modules into the control of the collections (e.g. omcollections)
- Added layout for adding a default editor customization to portal configuration file
- Removed omoccurlithostratigraphy field removed
> Paleo Development

- config/schema-1.0/dev/db_schema_patch_pending.sql
- config/schema-1.0/utf8/db_schema_patch-1.1.sql
> Paleo Adjustment

- js/symb/collections.harvestparams.js
- Form will now accept submissions even if only polygon is added into search form
> Occurrence Search Minor bug

- classes/SpecUploadBase.php
- collections/harvestparams.php
- content/lang/collections/harvestparams.en.php
- content/lang/collections/harvestparams.es.php
- js/symb/collections.occureditortools.js
- Minor specimen upload bug
- Minor bug fix to UTM format tool
- Readjustment of public search form text
> Misc layout adjustments and minor bug fixes

- classes/ImageProcessor.php
- classes/SpecProcessorOcr.php
- collections/editor/occurrenceeditor.php
- collections/specprocessor/ocrprocessor.php
- config/symbbase.php
- js/symb/collections.occureditormain.js
- Extended verbatim coordinate parsing
- Minor adjustments to iPlant default processing start date
- Misc adjustments
> Image Processing adjustments

- classes/ImageProcessor.php
- collections/specprocessor/imageprocessor.php
- Bug fix that blocked loading multiple image when only large image version is supplied without a web derivative
- Bug fix that blocked loading when extra non-mapped column are included in the upload file.
> Image Mapping debugging

- classes/TaxonomyHarvester.php
- Extra spaces being place within animalia infraspecific names
> Taxonomic Cleaning bug

- classes/OccurrenceEditorDeterminations.php
- classes/OccurrenceEditorManager.php
- collections/editor/batchdeterminations.php
- collections/editor/includes/determinationtab.php
- collections/editor/includes/imagetab.php
- collections/editor/occureditor.php
- collections/editor/occurrenceeditor.php
- collections/editor/rpc/getnewdetitem.php
- collections/loans/index.php
- collections/reports/annotationmanager.php
- Add option to queue records based on otherCatalogNumbers
- Various layout design changes
- Misc bugs
> Batch determination dev

- collections/editor/batchdeterminations.php
- collections/editor/rpc/index.php
- collections/reports/annotationmanager.php
- css/base.css
> Occurrence Determination Dev

- classes/OccurrenceIndividualManager.php
- classes/OccurrenceUtilities.php
- classes/SpecUpload.php
- classes/SpecUploadBase.php
- collections/admin/uploadreviewer.php
- collections/datasets/duplicatemanager.php
- collections/individual/index.php
- Finished adding support for depth variables
- Add depth variables to import tools
- Added depth variables to individual occurrence display page
> Specimen support

- classes/OccurrenceAttributes.php
- collections/editor/includes/traittab.php
- collections/traitattr/occurattributes.php
- Add true/false traitType (TF)
- Display trait label for a TF traitType
- Bug fix that failed to allow multiple dependent traits associated with a single state
> Occurrence Trait Dev

- classes/OccurrenceSesar.php
- Iniital management function for IGSN identifier assignments via the SESAR system
> SESAR IGSN Identifier development

- classes/OccurrenceSesar.php
- Continued develpment of class functions to assign and manage IGSN occurrenceID GUIDs
> SESAR IGSN Development

- classes/OccurrenceLabel.php
- Fixed bug that was failing to output taxon units (e.g. genus, specificEpithet, etc)
- Added new field with scientific name plus author
> Label Generator Dev

- classes/OccurrenceGeorefTools.php
- collections/georef/batchgeoreftool.php
- Added georeferenceProtocol field to batch georeferencing form (SoRo request)
> Batch Georef Dev

- classes/OccurrenceSesar.php
- classes/SpecUploadBase.php
- collections/admin/igsnmapper.php
- Create framework for GUID manager interface
- Add setter/getter functions for control variables
> IGSN GUID Management Dev

- classes/GlossaryUpload.php
- classes/ImageLocalProcessor.php
- classes/Manager.php
- classes/OccurrenceEditorManager.php
- classes/OccurrenceUtilities.php
- classes/SalixHandler.php
- classes/TaxonomyUpload.php
- collections/editor/rpc/nlpsalix.php
- misc/charencodingclean.php
- Removed some code fragments that was trying to translate Windows "smart"/curly quotes, but also ended up corrupting some valid UNICODE characters
> Character Set import bug

- classes/OccurrenceDuplicate.php
- classes/SpecUpload.php
- classes/SpecUploadBase.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Isolated batch import/updates into multiple IMPORT/UPDATE statement to avoid extended locks to occurrence table
- Initial modifications to support targetted characters set imports and MAC character set
- Add unique constraint for occurrenceID GUIDs
- Add remote port to logging of remote imports
- Filter out s.n. as collector number when searching for specimen duplicates
> Occurrence Import Dev and misc bugs

- classes/OccurrenceSesar.php
- collections/admin/igsnmapper.php
-Further development of IGSN functions and control panel
> SESAR IGSN GUID Managment Development

- classes/OccurrenceSesar.php
- collections/admin/igsnmapper.php
- Add output options
- Add XML response parser and analyzer
- Misc debugging and adjustments
> SESAR IGSN GUID Development

- classes/SpecUploadBase.php
- Fix to avoid out of memory php error
> Specimen Upload bug

- classes/OccurrenceSesar.php
- collections/admin/igsnmanagement.php
- collections/admin/igsnmapper.php
- collections/admin/rpc/getigsnseed.php
- Reconfigure management tools to support the establishment of set identifier generation profiles
> IGSN Management Development

- classes/OccurrenceEditReview.php
- collections/editor/editreviewer.php
- Improve SQL efficiency to reduce slow data return within large datasets
> Specimen Edit Review

- collections/individual/index.php
- collections/misc/collmetadata.php
- Added support for using otherCatalogNumbers to map to a source resource. Needed to map to dynamically link occurrences to NEON sample viewer
> Specimen Details display adjustments

- collections/individual/index.php
- Improve display of source identifier within link back to source records
> Occurrence Details adjustment

- collections/specprocessor/standalone_scripts/ImageBatchConf_template.php
- collections/specprocessor/standalone_scripts/ImageBatchHandler.php
- Added option to match on otherCatalogNumbers when linking image to an existing records. Needed for batch processing NEON images
> Batch Image Processing Development

- classes/ImageLocalProcessor.php
- Adjustments to better handle special characters within image filenames
> Batch Image Processing adjustments

- webservices/dwc/dwcapubhandler.php
- Added locality redaction check to download web service calls
> Download Web Service Dev

- classes/SpecUploadBase.php
- Adjust stat report to account for synchronization of records when updating a previous live managed collection that is now a snapshot due to transfer of management to new portal
> Occurrence Upload Dev

- classes/ImageProcessor.php
- collections/specprocessor/imageprocessor.php
- Catch and display CyVerse server offline error
- Minor bug fix with precessing date
> CyVerse Image Processing Adjustments

- classes/OccurrenceAttributes.php
- collections/editor/includes/traittab.php
-Bug fix to isolate edits per trait cluster
> Attribute Trait encoding

- classes/ImageLibraryManager.php
- classes/OccurrenceAttributes.php
- classes/OccurrenceSearchSupport.php
- collections/editor/includes/traittab.php
- collections/editor/occurrenceeditor.php
- collections/traitattr/attributemining.php
- imagelib/search.php
- Occurrence attribute adjustments
- Bug fix that caused SQL to final for portals with dynaicProperties added to omcollections table
- Modify code to  display No Image message when zero record return
> Occurrence Attribute Management dev and Image Search bugs

- imagelib/search.php
- js/symb/imagelib.search.js
- Move collections list out of its own tab and link display to Image Type selection
- Display message when no images match search criteria
> Image Search revamp

- classes/OccurrenceAttributes.php
- collections/editor/includes/traittab.php
- collections/editor/occurrenceeditor.php
- collections/editor/rpc/editorTraitHandler.php
- Isolated attribute deletion within trait management tab as an AJAX function
- Continued adding support for numeric traits
- Misc bugs and errors
> Occurrence Trait Management dev

- classes/OccurrenceDuplicate.php
- classes/OccurrenceEditorManager.php
- collections/editor/includes/paleoinclude.php
- collections/editor/includes/queryform.php
- collections/editor/occurrenceeditor.php
- collections/editor/rpc/getlocality.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- css/occureditor.css
- js/symb/collections.occureditormain.js
- Added editing support for DwC locationID for storage of unique identifiers that define a specific locality within a collection event
- Integrate locationID into locality lookup and quick-fill functionality.
- Define an index for eventID and locationID
> Occurrence Management Development

- checklists/nonvoucheredtab.php
- checklists/tools/mapboundingbox.php
- checklists/vamissingtaxa.php
- classes/OccurrenceSearchSupport.php
- collections/editor/includes/traittab.php
- css/main_template.css
- Bug fix that was failing to isolate specimen and occurrence searches
- Fix for map search display text
- Refresh button improvements
- Add support for second level submenus within header menu
> Various updates and bugs

- classes/SpecUploadBase.php
- Allow identification history record if identifiedBy, dateIdentified, OR scientificName is populated.
> Specimen Upload adjustment

- classes/TaxonomyEditorManager.php
- taxa/taxonomy/taxoneditor.php
- taxa/taxonomy/taxonomyloader.php
- Modified code to display different cross kingdom rank names for a given rankid
> Taxonomy Editor adjustment

- classes/OccurrenceAttributes.php
- Bug fix that was interferring with correct display of traits
> Attribute Adjustment

- agentauth/composer.lock
> Security patch from Symfony

- collections/editor/occurrenceeditor.php
- collections/georef/batchgeoreftool.php
- js/symb/collections.georef.batchgeoreftool.js
- js/symb/collections.occureditortools.js
> Georeferencing Adjustments

- classes/OmProtectedSpecies.php
- classes/SpecUploadBase.php
- Misc bug fixes to taxon search within protected species pages
- Adjustment to method determining image meme type
> Misc adjustments

- classes/OccurrenceCollectionProfile.php
- collections/misc/collmetadata.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Add collectionID to md management form
- Initial prep for adding datasetID, which will be used for tracking, linking, and GBIF/EML publishing of NEON sampleClasses
- general code cleaning
> Collection Metadata Manager adjustment

- classes/SpecUploadBase.php
- Finish implimenting support for determination sourceIdentifier that is needed for successful coordination of specimen annotations
> Update Determination History uploads

- js/symb/collections.coordinateValidation.js
- js/symb/collections.occureditormain.js
- Improve coordanate parser and converter function
- Avoid error when Google API associated tools are not activated
> Occurrence Editor adjsutments

- checklists/vamissingtaxa.php
- classes/ChecklistVoucherAdmin.php
- classes/ChecklistVoucherReport.php
- Bug fix that incorrectly displayed specimen vouchers ouside coordinate criteria within voucher linking tools
- Increase limit of displayed specimens to 1000
-Added order by scientific name within SQL statement
- Same improvements to efficiency of SQL statements
> Checklist Voucher Management Dev

- checklists/checklist.php
- js/symb/checklists.checklist.js
- Misc improvements in display of checklist metadata
- Minor code updates and function improvements
> Checklist adjustments

- classes/OccurrenceUtilities.php
- classes/SpecUploadBase.php
- Fix to Live collection uploads duplicating new records
> Occurrence Loading bug

- classes/OccurrenceIndividual.php
- classes/OccurrenceListManager.php
- collections/individual/index.php
- collections/individual/linkedresources.php
- collections/list.php
- content/lang/collections/list.en.php
- content/lang/collections/list.es.php
- Add locationID to output within occurrence details page
- Remove protected message from occurrence listing when approved user is signed in
- Move protected message into display model for occurrence listing page
- Move protected text into language files
> Occurrence details display adjustments

- classes/ImageLibraryManager.php
- Improvement to SQL efficiency
> Image Search mod

- collections/editor/occurrenceeditor.php
- js/symb/collections.occureditormain.js
- Bug fix and expansion of coordinate parsing algorithm
> Occurrence Editor

- classes/ImageCleaner.php
- Only build thumbnail for images that lack thumbnails (even if web/medium image is NULL)
> Image Thumbnail maintenance tool

- classes/SpecUploadBase.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Adjsuted code to accommodate databases that don't have a sourceIdentifier defined within the uploadimagetemp table
> Specimen Upload bug fix

- classes/ImageLibraryManager.php
- Improved image contributor stats page so that it used cached images counts rather than  grabbing stats from high load SQL queries
> Image Library Dev

- classes/OccurrenceCollectionProfile.php
- classes/PluginsManager.php
- collections/misc/collmetadata.php
- Fixed bug that was throwing fail error when a non-admin was trying to edit metadata
- Minor plugin adjustement to hide warning when removing files
> Collection Metadata Editor bug

- classes/SpecProcessorManager.php
- Improve SQL efficiency so that user stats are returned in a reasonable amount of time, even within large databases
> User Stats adjustment

- classes/SpecUpload.php
- classes/SpecUploadBase.php
- collections/admin/uploadreviewer.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Activated support for import of genetic sequence data. Expects import data to have GenBank or BOLD sequences linked to associatedSequences input field. Multiple URLs can be delimited using a comma, semicolon, or pipe.
- Misc adjustments to omoccurgenetic
> Occurrence Upload Development

- classes/ImageProcessor.php
- temp/data/.gitignore
- Populate image tid with current specimen ID code
- Misc adjustments
> Image Mapping Dev

- classes/OccurrenceUtilities.php
- Added leap year test for eventDate
- Added additional month testing to eventDate parser
> Occurrence Upload adjustments

- classes/OccurrenceUtilities.php
- classes/SpecUploadBase.php
- Improvement on date validation
- Improved validation of coordinateUncertaintyInMeters (no negatives)
- Bug fix with coordinate valiadation and verbatimCoordinates field
> Occurrence Import adjustments

- classes/OccurrenceSesar.php
- collections/admin/igsnmanagement.php
- collections/admin/igsnmapper.php
- collections/admin/rpc/syncigsn.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Completion of reconfiguration of IGSN assignment and mapping tool
- Addition of controls to assist in relinking orphaned IGSN
- Add IGSN Verification table so that I can enable more efficient IGSN verification and synchronization functions
> SESAR IGSN GUID Dev

- classes/OccurrenceSesar.php
- Switch from development to production mod
- Added toggle switch to for each transition between modes
> SESAR IGSN Management Dev

- classes/OccurrenceSesar.php
- collections/admin/igsnmanagement.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Reworked verification tools to use a temporary verification table for improved preformance
> IGSN Management Dev

- classes/OccurrenceListManager.php
- Only display first based on sort order
- Misc minor adjustments
> Occurrence List adjustment

- classes/OccurrenceAttributes.php
- collections/editor/includes/traittab.php
- collections/traitattr/occurattributes.php
- profile/index.php
- Adjustments to display placement of T/F character states
- Convert 'source' controled lookup list
- Add taxon, country, state, and source filter options to image coding tool
- Rework variable management within image coding tool
> Occurrence Attribute development

- classes/OccurrenceEditReview.php
- Fixed bug that interferred with downloads of editing reports
> Occurrence Review bug fix

- classes/DwcArchiverOccurrence.php
- webservices/dwc/dwcapubhandler.php
- Extend documentation detailing accepted variable wtihin the DWCA web service handler
> Occurrence Publishing

- classes/OccurrenceSesar.php
- Added sample_subtype to registration metadata; appears to be a newly required field
- Adjustment to accommodate new errors coming out of IGSN system
> SESAR IGSN management development

- classes/OccurrenceIndividual.php
- classes/OccurrenceListManager.php
- collections/individual/index.php
- collections/list.php
- Applied institution and collection code overrides within occurrence display page and occurrence list and table displays
> Occurrence display adjustments

- classes/OccurrenceCollectionProfile.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Make contact email address clickable
- Misc adjustments to image schema
> Collection Metadata display adjustments

- collections/georef/batchgeoreftool.php
- collections/traitattr/attributemining.php
- Modified locality SELECT list within batch georeferencer so that it can be resizable by user
- Modified locality SELECT list within batch occurrence trait mining tool so that it can be resizable by user
> Batch coding adjustments

- collections/datasets/datapublisher.php
- collections/datasets/datasetmanager.php
- collections/datasets/duplicatemanager.php
- collections/datasets/index.php
- collections/datasets/occurharvester.php
- collections/misc/assocmanagement.php
- collections/misc/collbackup.php
- collections/misc/collorderstats.php
- collections/misc/collpermissions.php
- collections/misc/collprofiles.php
- collections/misc/collstats.php
- collections/misc/collyearstats.php
- collections/misc/commentlist.php
- collections/misc/index.php
- collections/misc/occurrencesearch.php
- collections/misc/protectedspecies.php
- collections/traitattr/attributemining.php
- collections/traitattr/index.php
- collections/traitattr/occurattributes.php
- collections/traitattr/traitmanagment.php
- /collections/misc/
- /collections/datasets/
- /collections/traitattr/
> Adapts files to new framework structure

- classes/ChecklistAdmin.php
- classes/OccurrenceCollectionProfile.php
- classes/RdfUtility.php
- collections/datasets/datapublisher.php
- Adjustments to resolve GBIF publishing error when endpoint changes or fails to save
> DwC-A publishing to GBIF

- classes/OccurrenceCollectionProfile.php
- collections/datasets/datapublisher.php
- Minor adjustments to display messages
> DwC-Archive publishing adjustments

- classes/SpecUpload.php
- classes/SpecUploadBase.php
- collections/admin/uploadreviewer.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Integrated support for import of paleo data into the omoccurpaleo table
- Misc adjsutments to paleo support module
> Specimen Import Dev

- classes/SpecUpload.php
- classes/SpecUploadBase.php
- Added control that only outputs paelo terms when paleo module has been activated within the collection
> Occurrence Upload Developments

- classes/OccurrenceCollectionProfile.php
- Recent code changes failed to maintain a write DB connection when updating collection
> Collection Management bug

- classes/SpecUploadBase.php
- collections/admin/specupload.php
- Restrict function triggering when collection ID is not supplied or NULL
- Catch fatal paleo parsing  errors
> Occurrence Uploda bugs and security fixes

- classes/OccurrenceTaxaManager.php
- classes/TaxonomyDisplayManager.php
- classes/TaxonomyEditorManager.php
- taxa/taxonomy/rpc/gettaxasuggest.php
- taxa/taxonomy/taxonomydisplay.php
- Improved support for hybrid taxa
- Move db calls out of AJAX handlers and into class functions
- Misc code refactoring and improvements
> Taxonomy Editor Development

- taxa/taxonomy/taxoneditor.php
- Added support for tagging a taxon as extinct or hybrid
> Taxon Management Development

- collections/specprocessor/imageprocessor.php
- Minor adjustment to form validation
> Image Processor

- checklists/tools/mappolyaid.php
- classes/OccurrenceManager.php
- Add js code to close polygon when inserted into form
- Fix bug interferring with setting of polygon
> Checklist Voucher Management bug

- classes/ImageLibraryManager.php
- imagelib/index.php
- XSS injection fix
- Bug fix that interferred with matching name on synonyms
> Image Library modifications

- collections/harvestparams.php
> Occurrence Search minor adjustment

- checklists/checklist.php
- config/symbini_template.php
- profile/usermanagement.php
- projects/index.php
- taxa/index.php
- Converted display of Google Map static thumbnails to be options based on Symbiota configuration files
> Google Static Map Displays

- classes/TaxonProfile.php
- taxa/index.php
- Adding ability to display info for a non-accepted taxon that is linked to more than one accepted names
> Taxon Profile dev

- checklists/checklist.php
- checklists/checklistadmin.php
- checklists/dynamicmap.php
- checklists/rpc/index.php
- checklists/tools/checklistloader.php
- checklists/tools/index.php
- checklists/voucheradmin.php
- sitemap.php
- Remapped header.php file within  includes directory
- Remapped footer.php file within  includes directory
> Checklist dir modifications needed for new framework

- classes/TPDescEditorManager.php
- classes/TPEditorManager.php
- classes/TPImageEditorManager.php
- taxa/profile/tpeditor.php
- Support for adding and editing descriptions and images for non-accpeted taxa that have multiple accepted taxon links (e.g. invertebrate bycatch support)
- Misc code updates and refactoring
> Taxon Profile Developments

- classes/TaxonProfile.php
- css/symb/speciesprofile.css
- taxa/index.php
> Species Profile Adjustments

- classes/TPDescEditorManager.php
- classes/TPEditorManager.php
- classes/TPImageEditorManager.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- taxa/profile/tpdesceditor.php
- taxa/profile/tpeditor.php
- taxa/profile/tpimageeditor.php
- Refactoring old code
- Various bug fixes, variable sanitation, and style adjustments
> Taxon Profile Management Devlopment

- checklists/checklist.php
- classes/OccurrenceCollectionProfile.php
- collections/misc/collstats.php
- Added variable sanitation code to protect from SQL Injection attachs
> Collection Stats security patch

- classes/ImageProcessor.php
- collections/editor/occurrenceeditor.php
- collections/editor/occurrencetabledisplay.php
- collections/specprocessor/processor.php
- collections/specprocessor/standalone_scripts/ImageIPlantHandler.php
- taxa/index.php
- Misc adjustments to display output within multiple pages
> Misc minor adjustments

- classes/SpecProcNlpSalix.php
- classes/SpecUploadBase.php
- Data cleaning data check set to be more dynamic based on current date
> Data harvesting bug

- classes/ProfileManager.php
- config/symbbase.php
- Fix to login critteria failing to remain persistance, even when remember me was checked
> Permissions bug

- classes/TaxonomyHarvester.php
- Clean and escape special characters during data import
> Taxonomy Harvester bug

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- Fix to avoid occurrence records from being published multiple times within occurrence.csv file when record contained one-to-many relationships with extension data
> DwC-A Publishing bug

- classes/OccurrenceAttributes.php
- classes/OccurrenceCollectionProfile.php
- collections/traitattr/occurattributes.php
- Fix to Occurrence Attribute "skip" function
- Fix filter by country/state within Occurrence Trait image coding tool
- Collection profile display adjsutment to only display an IPT endpoint once when used multiple times within a complex import profile
> Various code fixes

- classes/ImageShared.php
- classes/SpecUploadBase.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Reset image derivatives when duplicate image supplied is set to replace previously loaded iDigBio or CyVerse images
> Data loading advancement

- classes/TaxonProfile.php
- taxa/index.php
- Fix to issue causing failure of data return when only a taxon string is provided
> Taxon Profile bug

- classes/OccurrenceCollectionProfile.php
- Mixed up display of ITP title with path
> Collection Profile bug

- classes/OccurrenceCollectionProfile.php
- config/symbbase.php
- Fix bug that was interferring with collection statistic function
> Collection Statistic bug

- collections/download/index.php
- includes/leftmenu_template.php
-Activate attribute download across all collections
> Occurrence Attribute Dev

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- collections/download/index.php
- Added higherClassification and verbatimTaxonRank
- Converted taxonRank to verbatimTaxonRank
- Populate taxonRank with rank names that are defined within TaxonUnits table
> Occurrence Export Development

- classes/OccurrenceTaxaManager.php
- Adjusted SQL statement for upper level taxonomic occurrence searches to make more efficiently use of indexes
> Occurrence Search modification

- classes/TaxonomyDisplayManager.php
- classes/TaxonomyEditorManager.php
- classes/TaxonomyUtilities.php
- Fixed bug that was occasionally failing to index direct parents for some taxa
- Added SQL to reset direct parents within taxaEnumTree index table
- Fixed bug to inprove display of non-accepted matches when whole word option is selected in taxonomic display page
> Taxonomic thesarurus management adjsutments

- collections/editor/includes/paleoinclude.php
- Added ability to conserve  inported values when they fail to match with controled lookup values
> Paleo Management Development

- checklists/voucheradmin.php
- classes/SpecUploadBase.php
- Catch occurrence upload error due to occurrenceID conflicts
- Add instruction message on entering multiple search terms within within search variable setup form
> Minor developments

- classes/ImageProcessor.php
- Added GUID building to image file mapping function to assign UUID to all new occurrences and image files
- Added logging to the upload image mapping file to keep track of file loads
- Remove file processing of iDigBio Media Ingestion reports since the appliance is no longer supported
> Image Processing Development

- classes/GamesManager.php
- games/ootd/index.php
- Added support on matching on synonyms
- Added variable sanitation for security
- Removed redundent code blocks
- Plugged into shared autocomplete function wtihin the api directory
- Fixed bug that was causing Organism of the day to refresh  when clid variable isn't submitted
> Refactorization of the Organism of the Day module

- classes/ImageLibraryManager.php
- classes/OccurrenceIndividual.php
- classes/OccurrenceSearchSupport.php
- collections/individual/index.php
- games/ootd/index.php
- imagelib/search.php
- Added search criteria to top of results page
- Improve sorting to based on scientific name whether it is indexed via the thesaurus our not
- Modified photographer citation to have photographer linked via the image table to override recordedBy listed within omoccurrence table
- Modified Specimen Details page to cite photographers that were different than the original collector
> Image Search Development

- classes/TPDescEditorManager.php
- classes/TPEditorManager.php
- classes/TaxonProfile.php
- taxa/profile/tpdesceditor.php
- taxa/profile/tpeditor.php
- Integrate adminlanguage table into taxa description manage tools
> Language support development

- classes/GamesManager.php
- classes/PluginsManager.php
- Code modification to make SSL certification testing for images more tollerant wtihin OOTD game setup under the asumption that images used will always be from a trusted source
- Started to removed inline css styling from within slideshow to give portal manager more control over styling
> Plugin and Game refactoring

- classes/PluginsManager.php
- Move image resizing into css style tag
> Plugin Development

- collections/download/index.php
- Replace table format with floatable divs
- Remove inline styling
- Prepare occurrence download to be integrated into occurrence dataset management
> Occurrence Download Development

- classes/OccurrenceDataset.php
- collections/datasets/datasetmanager.php
- Removed builting download code with plan on making use of occurrence download module used within occurrence listing pages
- Testing and furthering development of code
- Various debugging and code fixes
> Dataset Management

- classes/DwcArchiverCore.php
- classes/OccurrenceCollectionProfile.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- content/lang/collections/misc/collprofiles.en.php
- content/lang/collections/misc/collprofiles.es.php
- Added support for displaying multiple contacts with various roles.
- Schema modification to support storage of multiple contact data as a string representing a JSON object stored wtihint the contact field
> Collection Metadata Development

- classes/OccurrenceManager.php
- collections/individual/index.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Added multiple contact support to Occurrence Details page
- Adjustments to extention of multiple contacts stored as a string representation of a JSON object
> Occurrence Display Development

- classes/OccurrenceUtilities.php
- Additional improvement on eventDate parsing during data import
> Occurrence Import adjsutments

- classes/OccurrenceManager.php
- collections/datasets/datasetmanager.php
- js/symb/checklists.checklist.js
- Add query support for datasets
- Further development of dataset management
> Occurrence Search Development

- checklists/checklist.php
- classes/ChecklistManager.php
- classes/GamesManager.php
- content/lang/checklists/checklist.en.php
- content/lang/checklists/checklist.es.php
- projects/index.php
- Checklist Games bug fix
- Misc misspelling and wording adjustments
> Inventory Development

- classes/OccurrenceLoans.php
- collections/loans/exchange.php
- collections/loans/exchangetab.php
- collections/loans/incoming.php
- collections/loans/index.php
- collections/loans/outgoing.php
- collections/loans/reports/defaultenvelope.php
- collections/loans/reports/defaultinvoice.php
- collections/loans/reports/defaultmailinglabel.php
- collections/loans/reports/defaultspecimenlist.php
- collections/loans/reportsinclude.php
- js/symb/collections.loans.js
- Continuation and debugging code refactoring
- Variable sanitation for security
- Break up and modulate loan in/out and exchange transactions
> Loan Management development continued

- classes/TPEditorManager.php
- taxa/profile/tpeditor.php
- Added support searches for multiple homonym existing within system
- Fixed autocomplete feature within search term field
> Taxon Profile Editgor dev

- classes/SpecUploadDwca.php
- Minor adjustment to importing via SSL
> DwC-A Occurrence Harvesting adjustment

- checklists/checklist.php
- checklists/checklistadmin.php
- classes/ChecklistAdmin.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- content/lang/checklists/checklistadmin.en.php
- content/lang/checklists/checklistadmin.es.php
- Add ability to link to project from checklist metadata form (far easier)
- Trim and clean notes and additional data outputs
- Misc code cleaning and variable sanitation
> Checklist Management

- classes/SpecUploadBase.php
- Fixed issue that was interferring with the import of biostratigraphy term
> Paleo Module bug fix

- agents/index.php
- checklists/checklist.php
- checklists/checklistmap.php
- classes/ChecklistManager.php
- classes/InventoryProjectManager.php
- classes/MapSupport.php
- classes/OccurrenceMapManager.php
- classes/OccurrenceUtilities.php
- collections/map/mapbox.php
- config/symbini_template.php
- projects/index.php
- taxa/index.php
- Add option to display MapBox static maps as an alternative option to Google Map API services
- Integrate MapBox static map option into inventory project page
- Integrate MapBox static map option into checklist display page
- Begin integration of MapBox API into Taxon Profile map display
> MapBox Integration as Alternative to Google Map API

- classes/ImageLocalProcessor.php
- Further modifications to relax ssl certification verification when processing remote user images
> Image Processing

- classes/ImageLibraryManager.php
- config/dbconnection_template.php
- imagelib/index.php
Improve efficiencies of browsing workflow and SQL statements with the hope of reducing overhead, especially when site is being indexed by search bots
> Image Browser Dev

- classes/ImageLibraryManager.php
- imagelib/search.php
Sets sanitization that was missing for taxon parameter in image search and crtiteria display. Fixes vulnerability flagged by UTO.
> implements simple sanitization for image search

- classes/ImageLibrarySearch.php
- imagelib/search.php
> Image Library Search dev

- classes/ImageLibrarySearch.php
- classes/OccurrenceSearchSupport.php
- imagelib/search.php
- Enhansed variable sanitation
- Additional adjustments on debugging to previous submission
> Image Search Dev

- classes/ImageShared.php
- classes/OccurrenceEditorImages.php
- collections/editor/imageoccursubmit.php
- collections/editor/includes/imagetab.php
- Add option to map to remote thumbnails or web images
- Added option to skip creation of the medium web image
> Image Submission Modifications

- classes/ProfileManager.php
- content/lang/profile/index.en.php
- content/lang/profile/index.es.php
- profile/index.php
- Added ability to send emails via SMTP
- Added ability to login using email address as login name
- Misc code clean-up
- Improved error tracking
> User Profile Developments

- collections/editor/skeletalsubmit.php
- js/symb/collections.editor.skeletal.js
- zero out field values when field is hidden
> Skeletal data submit form dev

- classes/ImageCleaner.php
- Bug fix that interferred with listing of thumbnails needing to be processed
> Image Processing bug fix

- classes/ProfileManager.php
- Bug fix interfering with password reset function
> Profile Management

- collections/individual/index.php
-Standardize all field labels to Pascal-Case
> Specimen Display minor adjustments

- classes/OccurrenceEditorAssoc.php
- collections/editor/includes/resourcetab.php
- collections/editor/includes/traittab.php
- collections/editor/occurrenceeditor.php
- collections/editor/rpc/getAssocOccurrence.php
- In process of adding occurrence ossociation controls to occurrence editor
> Occurrence Association Development

- collections/admin/igsnmapper.php
- collections/editor/occurrenceeditor.php
- collections/reports/labelsword.php
- collections/specprocessor/cogetest.html
- Removed 32 character limit to catalogNumber field
- IGSN manager form validation bug
- Minor GeoLocate authenication testing page adjustments
> Occurrence Editor adjustment and misc minor adjustments

- classes/DwcArchiverCore.php
- collections/individual/index.php
- Added support to customize collection title DwC-A export
- Minor adjustment to species protection message displayed within occurrence public display
> DwC-A Occurrence Publishing dev

- config/schema-1.0/dev/db_schema_patch_pending.sql
- docs/INSTALL.txt
- Skema updates to key and glossary table structures
- Misc updates to INSTALL doc
> Skema Modifications

- collections/datasets/datapublisher.php
- Adjustments to batch publishing tool to help managers refresh only previously publiished collections
> Darwin Core Archive publishing

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- Integrated omoccuridentifiers table into specimen details page so that it displays associated identifiers.
> Occurrence Additoinal Identifier Support

- classes/KeyCharAdmin.php
- classes/KeyCharDeficitManager.php
- classes/KeyDataManager.php
- classes/KeyEditorManager.php
- classes/KeyMassUpdate.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- ident/tools/editor.php
- Resolved issue with characters not displaying within editor when site's default language preference is not available within character definitions
- Fixed heading and character sorting within editor
- Various modifications to key editor display
- Schema adjustments in preparation for future developments
> Identification key developments

- ident/tools/editor.php
> Key editor dev

- classes/GlossaryManager.php
- classes/PermissionsManager.php
- glossary/addterm.php
- glossary/glossaryloader.php
- glossary/index.php
- glossary/individual.php
- glossary/rpc/checkterm.php
- glossary/rpc/index.php
- glossary/rpc/taxalist.php
- glossary/sources.php
- glossary/termdetails.php
- profile/usermanagement.php
- Added Glossary Editor to permissions profiel
- Moved glossary AJAX calls into Glossary Manager class
- Fixed various bugs and code issues
> Glossary Development

- collections/specprocessor/standalone_scripts/media_scripts.php
- Added function to assist with transfer and remapping remote images to local image mount storage
> Image Maintenance scripts dev

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- Fix to connection being prematurely closed within DwcArchiveOccurrence class
> DwC-Archive Publishing bug

- classes/DwcArchiverPublisher.php
- Fix that was interferring listing of collection for batch publishing when a site doesn't have collections grouped within categories
> DwcArchivePublisher bug

- classes/OccurrenceUtilities.php
- classes/SpecUploadBase.php
- Integrated Specify terms into import tool to assist the ingestion of the raw Specify output formats
> Occurrence Importer

- classes/OccurrenceLoans.php
- collections/loans/specimentab.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Display catalogNumber and otherCatalogNumbers within the specimen listing page
- Relax requirement for collid to be set when linking specimens. This will assist linking specimens across collection within the NEON portal
- minor schema adjustment
> Loan Development

- collections/loans/incoming.php
- Integrate previous speicmen linkage developments into incoming listing page
> Loan Management Dev continued

- classes/OccurrenceListManager.php
- collections/list.php
- collections/listtabledisplay.php
- Separate decimal lat/long into individual fields and columns within the display pages
> Occurrence Search Listing adjustments

- classes/GlossaryManager.php
- glossary/individual.php
- Bug fix displaying relavent taxon links
> Glossary adjustments

- classes/OccurrenceLabel.php
- collections/reports/labeldynamic.php
- collections/reports/labelmanager.php
- collections/reports/labels.php
- Make custom label generation functional based on the input of a JSON label profile definition that is stored associated with the collection or users profiles
-- Add new page that dynamically build labels based on a JSON format definition
-- Integrate JSON label format into label manager tool
-- Created a field array to be used to generate SQL and column output for export, thus making it easier to add new columns
> Occurrence Label Development

- classes/OccurrenceLabel.php
- collections/reports/labeldynamic.php
- collections/reports/labelmanager.php
- collections/reports/labels.php
- collections/reports/labelsword.php
- Modification to label profile JSON schema
- Fully integrate dynamic label to replace previous web-based label printing. Default JSON is applied if collection label formats are not defined
- Move label block processing into set of recursive class functions
-  Adjustments to Word format to accommodate elevation field output
- Added various fields needed for vertebrate collections
> Label Management and Printing Developments

- classes/DwcArchiverCore.php
- Modify query on dateLastModified to work on combination of dwc:modified and symbiota:dateLastModified to better catch source vs portal modification date
> DWC Archive download

- classes/OccurrenceLabel.php
- collections/reports/labeldynamic.php
- collections/reports/labelmanager.php
- collections/reports/labels.php
- Bug fix expanding field span scope to include prefix and suffix
- Adjustments to label div width to allow support for various row count
- Misc bugs found testing within a production environment
> Specimen Label generation

- collections/reports/labeldynamic.php
- collections/reports/labelmanager.php
> Label Printing dev

- collections/reports/labelmanager.php
- Minor bugs and adjustments to layout and styling
> Label Printing developments

- collections/reports/labelmanager.php
- content/collections/reports/labeljson_template.php
> Occurrence Label Print Module dev

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- collections/specprocessor/geolocate.php
- collections/specprocessor/rpc/coge_getCount.php
- js/symb/geolocate.js
- Fixed bug that interferred with inclusion of some search terms
- Added culivationStatus (cultivation/captive status) to filter options and output
- Added establishmentMeans to output
- Improved handling of queries that include cultivation/captive status
> CoGe GeoLocate modifications

- collections/download/downloadhandler.php
- Missed including this file during previous submission
> Occurrence DWC export adjustment

- collections/specprocessor/rpc/coge_build_dwca.php
- Bug fix that was interferring with submission of coordinate data package streamed to a GeoLocate CoGe project
> GeoLocate CoGe module bug

- classes/OccurrenceUtilities.php
- classes/SpecUploadBase.php
- Fixed bug that was failing to properly analyze Specify formatted coordinates and place them within the decimal coordinates field
> Occurrence Import bug

- classes/OccurrenceLabel.php
- collections/reports/labeljsoneditor.php
- collections/reports/labelmanager.php
- Added permissions layers with different levels of access for each of the label profile categories
- Bug fix intereferring with adding new profiles
- Added variable sanitation
> Occurrence Label Developments

- classes/OccurrenceLabel.php
- collections/reports/labeljsoneditor.php
- collections/reports/labelmanager.php
- Adjustment that would allow creation of labeljson.php page when missing
- Added link to editor from label manager
- Added link to label managers from editor
> Occurrence Label Printing Dev

- collections/reports/labeldynamic.php
- collections/reports/labelmanager.php
- Fixed bug that was interfering with escaping special characters within the JSON placed within HEAD SCRIPT tag
- Misc minor bug and code fixes
> Occurrence Label module development

- classes/OccurrenceLabel.php
- collections/reports/labeldynamic.php
- collections/reports/labeljsoneditor.php
- Reapply content text output within divBlocks and insertion of classNames
- Bug fix within dynamic label generator that interfered within generation of collection and user based labels
- Convert special characers to html entities to avoid html form issues
> Occurrence Label Manager

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- js/symb/references.index.js
- references/authoreditor.php
- references/index.php
- references/refdetails.php
- Add reference/publication listing to Occurrence Display page
- Beginning refactoring of the reference tools
- Minor schema adjustments
> Reference Developments

- collections/specprocessor/standalone_scripts/imagerotator.php
- Add standalone php script that can be used to evaluate and rotate images on a server
> Add standalone php script

- classes/OccurrenceEditorManager.php
- classes/OccurrenceEditorResource.php
- classes/SpecUploadBase.php
- collections/editor/dev/occurdataentry.php
- collections/editor/dev/occureditor.php
- collections/editor/includes/resourcetab.php
- collections/editor/occurrenceeditor.php
- collections/editor/occurrencetabledisplay.php
- collections/editor/resourcehandler.php
- Continued developments and debugging of Occurrence Associations module
- Integrate controlled vocabulary tables into tools
- Adding an Occurrence Resource handler to deal with submitted data change requests
> Occurrence Associations developments

- classes/OccurrenceAssociations.php
- classes/OccurrenceEditorResource.php
- collections/editor/includes/resourcetab.php
- collections/editor/resourcehandler.php
- Added class function to add new associations
- Added class function to delete existing association
- Added form support to delete an association
- Added basisOfRecord input to add form
- Added taxonReference input to add form
- Added variable sanitation
- Misc bug fixes
> Occurrence Associations

- classes/OccurrenceEditorManager.php
- classes/OccurrenceEditorResource.php
- collections/editor/includes/resourcetab.php
- taxa/index.php
- Bug fix interferring with display of full collection lookup list
- Bug fix issue with collection filtering
- Bug fix with assignment of correct relationship
- Bug fix with sorting of relationship lookup
> Occurrence Association debugging

- classes/OccurrenceEditorResource.php
- collections/editor/includes/resourcetab.php
- Restrict one from creating an occurrence relationsip to itself
- Extend form validation to ensure a relationship subject is defined
- Fixed displaying of who and when an assoication was recorded
- Misc variable and styling adjustments
> Occurrence Associations debugging

- classes/OccurrenceEditorResource.php
- classes/OccurrenceIndividual.php
- collections/editor/includes/resourcetab.php
- collections/individual/index.php
- Bug fix that interferred with display of associate catalogNumber when inverse relationship exists
- Various adjustments
> Occurrence Association dev

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- collections/individual/index.php
- Added associatedOccurrences to DwC-A output
- Adjusted occurrence display to include return of data when a non-UUID GUID is assigned
> DwC-A Occurrence Publishing Development

- collections/loans/incoming.php
- collections/loans/outgoing.php
- Added date validation since Safari doesn't support date input types, and thus any date format could be entered which could cause SQL errors
> Loan managment adjustments

- collections/exsiccati/index.php
- references/index.php
- Adjustment to various option box  stylings
> Minor styling issues

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- Fixed sql bugs that were blocking display of  references
- Misc styling adjustments
> Occurrence public display adjustments

- classes/OccurrenceManager.php
- content/collections/reports/labeljson_template.php
- Modified datasetid variable input to allow for mulitple dataset IDs delimited by commas
> Occurrence Search adjustment

- collections/specprocessor/standalone_scripts/imagerotator.php
- Added different verbose output formats
- MIsc minor adjustments
> Image Rotator Script dev

- classes/OccurrenceDataset.php
- collections/datasets/datasetmanager.php
- collections/datasets/index.php
> Dataset Dev

- classes/ChecklistVoucherAdmin.php
- classes/ExsiccatiManager.php
- classes/OccurrenceDuplicate.php
- classes/OccurrenceEditorManager.php
- classes/OccurrenceLabel.php
- classes/OccurrenceManager.php
- classes/OccurrenceSupport.php
- Added "little" to fullindex exclusion list
> Occurrence Search

- classes/DwcArchiverCore.php
- docs/CHANGELOG.md
- Added multiple contact support to DwC-A EML file (e.g. ResponsibleParty)
> Collection Metadata Dev

- classes/DwcArchiverCore.php
- Bug fix that was interferring with download of datasets (via datasetid)
> DwC-A Download Module

- classes/OccurrenceDataset.php
- collections/datasets/datasetmanager.php
- collections/datasets/index.php
- collections/datasets/rpc/getuserlist.php
- profile/occurrencemenu.php
- profile/viewprofile.php
-Final development and proofing
-Complete ability to link users to datasets
-Various bug fixes
> Occurrence Dataset Management Dev

- classes/OccurrenceDataset.php
- classes/OccurrenceListManager.php
- classes/OccurrenceManager.php
- collections/datasetinclude.php
- collections/datasets/datasetHandler.php
- collections/datasets/index.php
- collections/datasets/rpc/getuserlist.php
- collections/list.php
- Finish integrating occurrence dataset submition in the occurrence search listing page
- Refactor occurrence to dataset linking code
> Dataset Management Development

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- collections/individual/linkedresources.php
- Refactor dataset listing within occurrence display page
- Make use of datasetHandler page setup for central dataset management
- Design adjustments to make dataset and voucher listing clearer
> Occurrence Dataset Dev

- classes/ImageCleaner.php
- classes/ImageShared.php
- classes/OccurrenceEditorManager.php
- imagelib/admin/thumbnailbuilder.php
- Added option to evaluate EXIF orientation tag and rotate image derivatives whenever image is physically turned sideways with orientation tag set
> Image Maintenance Tool Development

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- content/lang/profile/index.en.php
- content/lang/profile/index.es.php
- profile/index.php
- Rework how multiple other catalog numbers are displayed within occurrene display page
- Minor layout adjustments to login page
> Occurrence Display and other minor adjustments

- checklists/clsppeditor.php
- classes/OccurrenceIndividual.php
- collections/datasets/datasetmanager.php
- collections/datasets/index.php
- collections/individual/linkedresources.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Continue finalizing and debugging tools
- Refactor display of datasets within occurrence individual page
> Dataset Management Dev

- classes/ProfileManager.php
- collections/datasets/datasetmanager.php
- collections/datasets/index.php
- profile/occurrencemenu.php
- Bug fix that was displaying occurrence projects within My Profile occurrence management tab when a user had no special permissions
- Various minor adjustments to display layout within dataset mangement tools
> Occurrence Management dev

- classes/TaxonomyHarvester.php
- Modification to Catalog of Life harvesting to adjust to change in the output structure of their JSON output
> Occurrence Taxonomy Cleaning tool bug fix

- collections/individual/index.php
- collections/specprocessor/standalone_scripts/imagerotator.php
- Bug fix of the display of dynamic link that opens external sample viewer when otehr catalog numbers are used as the central identifier
> Occurrence Profile page debugging

- classes/DwcArchiverCore.php
- Fix EML bug which was interferring wtih display of names of collection contacts
- Added surName and givenName to EML output
- Exclude display of null address elements
> DwC-Archive Publishing

- collections/reports/labelprofile.php
- Added JS function that can be used to inset JSON str into editor
> Specimen Label Editor adjustment

- collections/reports/labelprofile.php
- Added js function to insert target JSON into JSON gui editor
> Specimen Label Profile dev

- classes/ExsiccatiManager.php
- collections/editor/rpc/exsiccatisuggest.php
- collections/exsiccati/batchimport.php
- collections/exsiccati/index.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Add column to store IndExs identifier
- Integrated exsiccati suggest into exsiccati class file
- Add link back to IndExs resource when identifier is present
- Misc modifications to presentation of exsiccati record
> Exsiccati Dev

- collections/editor/includes/queryform.php
- Added language field to search options
> Occurrence editor search modifications

- classes/MediaResolutionTools.php
- collections/misc/collmetadata.php
- collections/specprocessor/standalone_scripts/imagerotator.php
- collections/specprocessor/standalone_scripts/media_scripts.php
- Debugging and proofing scripts since image migration tool has been added
> Image maintenance script dev

- classes/MediaResolutionTools.php
- collections/specprocessor/standalone_scripts/media_scripts.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Various code adjustment to resolve image archival tool
> Media Resolution tool debugging

- collections/editor/includes/imgprocessor.php
- js/jquery.imagetool-1.7.js
- js/symb/collections.editor.imgtools.js
- Add feature that allows user to rotate any image via JS
- Remove iPlant image rotation tool due to no longer need for it
- Adjustments to image zoom tool to account for rotated image
> Occurrence Editor Image Tool Development

- checklists/dynamicchecklist.php
- checklists/dynamicmap.php
- Security patch for a Cross-site scripting vulnerability
> Checklist bug

- collections/reports/labelmanager.php
- collections/reports/labelsword.php
- Debug php request terms to match adjsuted form elements
- Debug javascript to match form elements
> Occurrence Label Module

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- collections/specprocessor/reports.php
- Add code to make ORCIDs actionable when they are embedded into collection (recordedBy) or identifer names (identifiedBy)
- Misc improvements to layout
> Occurrence Profile development

- classes/ExsiccatiManager.php
- collections/exsiccati/index.php
- Add variable sanitation
- Add sourceIdentifer to output
- Bug fix that inhibited CSV output to be limited to title/number combinations without linked specimens
> Exsiccati Index Developments

- classes/ExsiccatiManager.php
- Bug fix that produced bad SQL when search term was supplied within an exsiccati search
> Exsiccati index bug

- classes/ExsiccatiManager.php
- Minor fix to previous code submit
> Exsiccait indexing bug

- config/schema-1.0/dev/db_schema_patch_pending.sql
- Add various fields to occurrence table
> Schema Adjustments

- checklists/dynamicchecklist.php
- classes/DynamicChecklistManager.php
- Fixed bug causing tool to fail that was introduced when adding variable sanitation code
- Added code to ensure taxon filter being applied during various methods of applying a taxon terms
- Extended Manager class into Dynamic Checklist class
> Dynamic Checklist Generator dev

- config/schema-1.0/dev/db_schema_patch_pending.sql
- Add unique indexes for occurrence assoications
- SQL bug fix
> Schema Modifications

- collections/individual/index.php
- Modified link out to prefer NEON sampleID when multiple otherCatalogNumbers exist
> Occurrence Display adjustment

- collections/editor/occurrencetabledisplay.php
- collections/editor/skeletalsubmit.php
Add null to processing status and language
> Add null values to skeletal file create

- classes/TaxonomyHarvester.php
- Fixed issue with failing to properly add and link parent taxa. Issue originated from COL limiting classification hierarchy within all output
> Taxonomy Cleaning debugging

- collections/individual/index.php
- includes/googleanalytics.php
- Minor adjustments to previous submit
> Google Analytic updates

- classes/OccurrenceGeorefTools.php
- Caching SQL statement that could be used to batch import external georeferencing events
> Georeference Dev

- config/schema-1.0/dev/db_schema_patch_pending.sql
- Add organismID and materialSampleID to occurrence table
- Add includeInSearch to occurrence dataset table
> Schema Patch Dev

- classes/ImageDropBox.php
- Class will be used to process images dropped within a DropBox file request
> DropBox image processing class

- classes/OccurrenceLoans.php
- collections/loans/outgoing.php
- Add support to occurrence listing module the ability to match other catalog numbers residing within omoccuridentifiers table
> Occurrence Loan Development

- checklists/tools/checklistloader.php
- classes/ChecklistManager.php
- Issue dealing with morpho-species output
- Various wording adjustments
> Checklist Export debugging

- taxa/taxonomy/taxonomydynamicdisplay.php
- Fixed autocomplete function within dynamic taxonomy display page
> Taxonomy Display bug

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- Soft occurrence association output (e.g. ecologicallyOccursWith: Pinus ponderosa) targets dwc:associatedTaxa
- Occurrence association output that references other occurrences targets dwc:associatedOccurrences
> Darwin Core Archive developments

- checklists/dynamicmap.php
- Added options to predefine lat and long centroid and zoom level
> Dynamic Mapping tool development

- classes/PermissionsManager.php
- classes/Person.php
- classes/ProfileManager.php
- js/symb/profile.viewprofile.js
- profile/newprofile.php
- profile/userprofile.php
- profile/viewprofile.php
-Added ability to link one's user account to an ORCID, or another GUID
> User Account development

- classes/OccurrenceExsiccatae.php
- collections/editor/rpc/exsiccatisuggest.php
- collections/exsiccati/batchimport.php
- collections/exsiccati/index.php
- Add sourceIdentifier to add and edit forms
- Rename class manager to place within occurrence group
> Exsiccatae Development

- classes/OccurrenceGeorefTools.php
- collections/georef/batchgeoreftool.php
- Cache country, state, county, and municipality lookup values to increase efficiency and speed of refreshing page after a georef event
> Batch Georeference Tool Development

- collections/georef/batchgeoreftool.php
- Cache processing status lookup select list results within georeferencing form to avoid having to rebuilt list every time records are georeferenced
- Added variable sanitation
> Batch Georeferencing Tool developments

- ident/key2.php
- Refactoring identification key layout
- General code updates
> Identification Key dev

- collections/editor/includes/queryform.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Schema update
- Editor search form minor update
> Various Minor Updates

- classes/OccurrenceExsiccatae.php
- collections/exsiccati/index.php
- Bug fix with display of merge lookup list values
- Misc styling adjustments
> Exsiccatae Management development

- css/base.css
- Remove identification styling which will be defined within a separate css file dedicated to key and checklist pages
> base CSS modifications

- collections/harvestparams.php
- content/lang/collections/harvestparams.en.php
- content/lang/collections/harvestparams.es.php
- Move header styling into head style definition
- Move text into language configuration files
- Various minor adjustments to occurrence trait search elements
> Occurrence Harvester Developments

- classes/SpecUploadBase.php
- Add exsiccataeIdentifier and exsiccataeNumber terms to translation list
> Occurrence Upload Adjustment

- classes/OccurrenceLoans.php
- collections/loans/outgoing.php
- collections/loans/specimentab.php
- Added option to download specimen list as a CSV output file
> Specimen Loan development

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- collections/editor/occurrenceeditor.php
- Added support to output of exsiccatae data into occurrenceRemarks
> DwC Archive Publishing Development

- classes/KeyDataManager.php
- ident/key.php
- ident/key2.php
- Code refactoring and design changes continued
> Identification Key Development

- classes/OccurrenceIndividual.php
- collections/individual/index.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Integrate Occurrence traits/attribute encodings via a trait tab within the Occurrence Details page
- Schema modifications to support private/public display, project groupings, and exclude from search
> Occurrence Details Development

- js/symb/collections.labeljsongui.js
- Adds a dropdown in the "line" editor to select a spacing to be added to the left of each line in the visual label format editor
> adds line left spacing option in label gui

- classes/OccurrenceEditorManager.php
- Adjustment to relationship lookups to avoid form failure when relationship lookup tables are not yet established
> Occurrence Relationship Clone Tool dev

- collections/harvestparams.php
- ident/key2.php
- Integrate vernacular control variable within central configuration file into occurrence search and identification keys
> Vernacuar Function adjustments

- classes/OccurrenceGeorefTools.php
- Exclude trimmed empty strings that were not filtered out by NULL values within the SQL query
> Occurrence Batch Georeferencing

- classes/OccurrenceGeorefTools.php
- collections/georef/batchgeoreftool.php
- Bug fix interfering with proper exclusion of empty string locality records
> Batch Georeferencing debugging

- classes/KeyDataManager.php
- classes/KeyMatrixEditor.php
- ident/admin/chardetails.php
- ident/admin/headingadmin.php
- ident/admin/index.php
- ident/admin/taxonomylinkage.php
- Bug fix that excluded characters that are not assigned to a grouping/heading
- Various form layout adjustments
> Taxon Character Management Tools

- classes/SpecProcDuplicates.php
- collections/specprocessor/duplicateharvest.php
- Continued development and debugging in an effort to create a prototype
> Specimen Duplicate Harvesting tool

- ident/key2.php
- minor adjustments to images positioning and display
> Identification key adjustments

- classes/ImageProcessor.php
- collections/specprocessor/imageprocessor.php
- collections/specprocessor/processor.php
- Added checkbox option to control if new records are created if catalog number fails to match an existing record. Default is not to create a new record.
> Image Mapping Tool dev

- classes/GlossaryManager.php
- glossary/index.php
- glossary/individual.php
- glossary/termdetails.php
- js/symb/glossary.index.js
- Refactoring of the image/illustration submission and management code
- Code reductions
- Various improvements and bug fixes
> Glossary Developments

- classes/SpecUploadBase.php
- Added support for uploading dwc:locationID
- Added function that dynamically build UPDATE and INSERT transfer SQL based on union of uploadspectemp and omoccurrence tables. This will provide additional support for adding additional fields at a later date.
> Occurrence Upload Devlopment

- classes/OccurrenceAttributeSearch.php
- classes/OccurrenceManager.php
- collections/harvestparams.php
- Changed form submit to code occurrence traits stateID as a single array under input name called attr
- attr variable passed as stateIDs concatenated by commas
- Minor display adjustments
> Occurrence Trait Search Developments

- collections/map/index.php
- collections/map/occurrencelist.php
- css/symb/collection.css
- js/symb/collections.map.index.js
- Bug fix issue with copy URL feature
> Dynamic Map Dev

- classes/TaxonomyCleaner.php
- classes/TaxonomyHarvester.php
- collections/cleaning/taxonomycleaner.php
- Initial steps for integrating Index Fungorum into taxonomy cleaning tools
> Taxonomy Cleaner dev

- classes/OccurrenceLoans.php
- collections/loans/specnoteseditor.php
-Minor adjustment to previous submit
> Loan Management

- collections/datasets/duplicatemanager.php
- collections/editor/dupesearch.php
- collections/individual/index.php
- collections/misc/collprofiles.php
- config/symbini_template.php
- css/occureditor.css
- Add link to Exsiccatae listing and exsiccatae download tools
- Add global variable to central configuration file to control activation of specimen duplicate tools
> Specimen Exsiccatae development

- collections/editor/includes/geotools.php
- css/occureditor.css
- Fix bug that was interfering with DMS/UTM to lat/lng decimal degree conversion tool
> Occurrence Editor Bug fix

- classes/OccurrenceEditReview.php
- collections/editor/observationsubmit.php
- js/symb/collections.editor.observations.js
- Various display format adjustments
- Misc minor bug issues
> Photo Observation submit tool

- collections/editor/occurrenceeditor.php
- collections/misc/collprofiles.php
- Misc adjustments to query variable assignment methods
> Occurrence Management

- classes/OccurrenceEditorManager.php
- collections/editor/occurrenceeditor.php
- js/symb/collections.editor.main.js
- profile/occurrencemenu.php
- Rework clone tool so that it works more like the old record clone options, but with the added functionality
- Reset session query variable each time management menus are accessed
- Bug fix with catalogNumber increment tool
- Bug fix resetting collection metadata when transferring to a new collection
> Occurrence Clone tool development

- classes/DwcArchiverCore.php
- classes/OccurrenceEditorManager.php
- classes/OccurrenceIndividual.php
- collections/datasets/datasetmanager.php
- config/schema-1.0/dev/db_schema_patch_pending.sql
- Add description field to occurrence dataset table
- Strip html tags from metadata pushed into DwC-A XML output file
- Allow SuperAdmin to access and edit occurrence dataset definitions
- Bug fix: Only display exsiccati panel in individual occurrence tab if there are other exsiccati linked to same number
> Misc bugs and minor adjustments

- profile/userprofile.php
- Remove requirement for ORCID identifiers
> User Profile bug

- classes/DwcArchiverPublisher.php
Minor adjustment to extended portal paths
> Darwin Core publishing

- classes/DwcArchiverOccurrence.php
- Add eventID to DwC-A publishing output file
> DwC-Archive Publishing Dev

- classes/OccurrenceIndividual.php
- classes/OccurrenceMapManager.php
- classes/ProfileManager.php
- imagelib/imgdetails.php
- Add code to valuate link protocols and include https when site is secured with an SSL certificate
> Adjustments to various site link

- config/schema-1.0/utf8/db_schema_patch-1.2.sql
- docs/CHANGELOG.md
- docs/INSTALL.md
- db_schema_patch-1.2 moved from development to applied
> Database schema developments

- classes/OccurrenceUtilities.php
- config/schema-1.0/dev/db_schema_patch-dev.sql
- Change latestDateCollected to eventDate2
- Added function to check initial format of input dates
- Add cleaning support for eventDate2 input
> Occurrence Cleaning function dev

- checklists/checklist.php
- checklists/checklistadmin.php
- checklists/vaconflicts.php
- checklists/vamissingtaxa.php
- config/symbbase.php
- config/symbini_template.php
- content/lang/checklists/vaconflicts.en.php
- js/symb/checklists.checklist.js
- Adjust persistence of editing tools
- Language translations fixes
- Fix game dropdown issue
> Checklist bugs and dev

- classes/OccurrenceDuplicate.php
- classes/OccurrenceEditorManager.php
- collections/editor/occurrenceeditor.php
- js/symb/collections.editor.main.js
- Debug issue of coordinates being appended to locationID
> Occurrence Editor bug issue

- config/schema-1.0/dev/db_schema_patch-dev.sql
- config/symbini_template.php
- Agent table development continued
> Schema Development

- classes/TaxonomyCleaner.php
- classes/TaxonomyHarvester.php
- collections/cleaning/taxonomycleaner.php
- Adjust method of coordinating taxon rankIDs so that they are more in line with taxon ranks defined with taxonranks table
- Accept inclusion of taxa even if the taxon rankID fails to be returned
> Taxonomic Cleaning dev

- classes/TaxonomyCleaner.php
- classes/TaxonomyHarvester.php
- collections/cleaning/taxonomycleaner.php
- Handle section and subsection differently depending on kingdom equaling Animalia or Plantae, Fungi
> Taxonomy Cleaning dev

- classes/TaxonomyHarvester.php
- classes/TaxonomyUpload.php
- taxa/taxonomy/batchloader.php
- Extension, debugging, and completion of functionality to harvest a taxonomic node via the WoRMS API
> Taxonomy Harvesting dev

- classes/TaxonomyHarvester.php
- classes/TaxonomyUpload.php
- taxa/taxonomy/batchloader.php
- Added taxonomic rank limit
- Misc debugging and adjustments
> Taxonomy harvester

- classes/OccurrenceLabel.php
- collections/reports/labeldynamic.php
- Allow minor formatting tags within label header and footer
- Minor bug fix to avoid warning/notice output to log file
> Label Formatter adjustments

- classes/OccurrenceLabel.php
- Fixed bug that interfered with creation of new collection or user based label profiles when profile is initially empty
> Label format tool development

- profile/usermanagement.php
> User Management modifications

- classes/PermissionsManager.php
- classes/Person.php
- classes/ProfileManager.php
- profile/newprofile.php
- profile/userprofile.php
- profile/viewprofile.php
- Removed biography, URL, address, and isPublic from user profile management. These provide little benefit to the portals, and are regularly abused by spammers
> Profile Management Modifications

- collections/misc/collpermissions.php
- Converted input submit buttons into <button> elements
> Collection Permission dev

- collections/admin/specupload.php
- Convert input submits to button submits
- Misc syntax bugs
> Specimen Upload

- collections/index.php
- collections/map/index.php
- content/lang/collections/index.en.php
- content/lang/collections/index.es.php
- content/lang/collections/index.fr.php
- content/lang/collections/sharedterms.en.php
- content/lang/collections/sharedterms.es.php
- content/lang/collections/sharedterms.fr.php
- Add link to all collection listing to the collection selection page
> Occurrence Search listing

- content/lang/checklists/checklistadminchildren.es.php
- content/lang/checklists/checklistadminmeta.es.php
- content/lang/checklists/checklistmap.es.php
- content/lang/checklists/clsppeditor.es.php
- content/lang/checklists/dynamicmap.es.php
- content/lang/checklists/vaconflicts.es.php
- content/lang/checklists/vamissingtaxa.es.php
- Add Spanish placeholder files containing English translations until the Spanish files are made available.
> Multi-language support development

- classes/OccurrenceLabel.php
- collections/reports/labelmanager.php
- collections/reports/labelprofile.php
- Display editor and clone options for all user types
- Various layout adjustments
> Label Printing adjustments

- classes/OccurrenceLabel.php
- Allow users to print labels outside of their user profile from within a Research Observation project
> Label Developments

- classes/OccurrenceCollectionProfile.php
- classes/OccurrenceIndividual.php
- collections/misc/collmetadata.php
- collections/misc/collmetaresources.php
- content/lang/collections/misc/collmetadata.en.php
- content/lang/collections/misc/collmetadata.fr.php
- Remove edit/add/display  support for individual contact, email, and homepage fields
> Collection Profile Management

- classes/TaxonomyUtilities.php
- provide better taxon parsing support for hybrid and extinct taxa
> Taxonomy Parser bug

- classes/TaxonomyDisplayManager.php
- config/schema-1.0/dev/db_schema_patch-dev.sql
- Improve taxon search to improve matching of hybrids and extinct taxa
> Taxonomy Management dev

- collections/admin/specupload.php
- Upload profiles were failing to save
> Occurrence Upload bug fix

- classes/GeographicThesaurus.php
- collections/georef/thesaurus.php
- Basic infrastructure for managing the geographic thesaurus
> Geographic Thesaurus dev

- classes/OccurrenceEditorMaterialSample.php
- classes/RpcBase.php
- classes/RpcUsers.php
- collections/editor/editProcessor.php
- collections/editor/includes/config/materialSample.css
- collections/editor/includes/config/materialSampleVars.php
- collections/editor/includes/materialsampleinclude.php
- collections/editor/rpc/getUsers.php
- Continued development and debugging of material sample tab and support functions and rpc calls
> Material Sample Dev

- classes/OccurrenceCollectionProperty.php
- collections/misc/collectionproperties.php
- config/schema-1.0/dev/db_schema_patch-dev.sql
- Continue development of user interface that will be used to setup override variables, activate/deactivate modules, define label profiles, and setup custom editor form layouts
> Collection Special Properties dev

- classes/GeographicThesaurus.php
- collections/georef/thesaurus.php
- Continued development and debugging
> Geographic thesaurus management development

- classes/ChecklistLoaderManager.php
Remove utf8 BOM character from first field of header
> Checklist loader

- classes/OccurrenceEditorImages.php
- classes/OccurrenceEditorManager.php
- collections/editor/includes/imagetab.php
- Rework how image tags are displayed and managed.
- Bug fix that was displaying duplicate tags within the editor when they are selected
> Image Management dev

- classes/TPImageEditorManager.php
- classes/TaxonProfile.php
- Internal photographer failing to display when override photographer is Empty Value, rather than NULL
> Taxon Profile bug fixes

- classes/DwcArchiverCore.php
- classes/DwcArchiverDetermination.php
- classes/DwcArchiverImage.php
- Fix issue with number of columns not matching meta.xml file
> DwC-A Download debugging

- classes/TaxonProfile.php
- Minor adjustment to taxon links display
> TaxonProfile adjustments

- collections/datasets/datapublisher.php
- Minor adjustment to resolve error
> Dataset Publishing

- classes/DwcArchiverCore.php
- classes/SpecUploadBase.php
- classes/SpecUploadDwca.php
- Update image extension file so that it maps to the Audubon Core media standard
- Add creator to import automapping feature
> Publishing and import dev

- classes/TaxonomyHarvester.php
- taxa/taxonomy/batchloader.php
- Continued development on integrating Catalog of Life into taxon node harvester
> Taxonomy Upload development

- classes/TaxonomyHarvester.php
- classes/TaxonomyUpload.php
- taxa/taxonomy/batchloader.php
- Various adjustments to information display and general layout
> Taxonomy Loader developments

- collections/editor/includes/queryform.php
- collections/misc/collmetadata.php
- content/lang/collections/editor/includes/queryform.fr.php
- Convert INPUT submits to BUTTON submits
- Query form French language bug
> Various minor bug fixes

- classes/DwcArchiverOccurrence.php
- Add labelProject to DwC Archive output, but only to backup and Symbiota schema with extended equals to true
> DwC Archive Publishing dev

- content/lang/collections/editor/includes/admintab.en.php
- content/lang/collections/editor/includes/admintab.es.php
- games/where/WhereInTheWorld.html
- games/where/classes/GamesWhereManager.php
- games/where/rpc/WhereInTheWorld.php
- ident/admin/index.php
- Continued integration of Daryl Lafferty's Where in the World game that is based on occurrence data
> Where in the World Game Development

- taxa/taxonomy/taxonomydynamicdisplay.php
- Expand select node to display children
- Scroll so that target is placed near top of node
- Remove irrelevant code
> Dynamic Taxonomic Tree adjustments

- classes/GeographicThesaurus.php
- content/lang/sitemap.en.php
- content/lang/sitemap.es.php
- content/lang/sitemap.fr.php
- geothesaurus/harvester.php
- geothesaurus/index.php
- sitemap.php
- Add tool to assist in migrating old geographic lookup tables into new geographic thesaurus
- Add geographic thesaurus management link to sitemap, but not yet activated
> Geographic Thesaurus developments

- classes/OccurrenceSesar.php
- collections/admin/igsnverification.php
- minor adjustments to remove dependency on select of a collection
> IGSN management

- classes/OccurrenceDuplicate.php
- classes/RpcOccurrenceEditor.php
- collections/editor/occurrenceeditor.php
- collections/editor/rpc/dupequerycatnum.php
- collections/editor/rpc/dupequeryothercatnum.php
- js/symb/collections.editor.tools.js
- Other catalog numbers duplicate search functions modified to include omoccuridentifiers table
- Catalog number duplicate search functions moved from inline into jQuery document setup functions
> Occurrence Editor developments

- collections/editor/occurrenceeditor.php
- css/symb/occurrenceeditor.css
- Adjust default width of identifier name/tag and value fields
> Occurrence editor minor adjustments

- classes/OccurrenceEditorMaterialSample.php
- collections/editor/includes/materialsampleinclude.php
- config/schema-1.0/dev/db_schema_patch-dev.sql
- config/schema-1.0/utf8/db_schema_patch-1.2.sql
- css/symb/occureditormaterialsample.css
- Continued debugging and adjustments based on  deployment within production environment
> Material Sample developments

- api/app/Http/Controllers/InstallationController.php
- Installation registration dev continued
> API development

- api/app/Http/Controllers/InstallationController.php
- Bug fix initiating handshake after registering remote
- Add GUID check between supplied and returned remote GUIDs
- Improve error catch when bad path is supplied
> API installation-handshake Development

- api/app/Http/Controllers/InstallationController.php
- Added return handshake just to insure initiator has registered target remote
- Added check to make sure touch isn't referring to self. No need to register self
- Fixed url for asynchronous handshakes
> API Installation development

- api/app/Http/Controllers/InstallationController.php
- Make sure not to register self when obtaining reference of self from remote library
> API Installation dev

- classes/SpecUpload.php
- classes/SpecUploadDwca.php
- collections/admin/specupload.php
- Added function to handshake with remote portal when an import is being conducted via a direct import via the remote portal
> Specimen Upload Developments

- classes/TaxonomyCleaner.php
- classes/TaxonomyEditorManager.php
- classes/TaxonomyHarvester.php
- classes/TaxonomyUpload.php
- Record who edits a taxonomic acceptance
> Taxonomy Adjustments

- classes/DwcArchiverOccurrence.php
- classes/OccurrenceEditorManager.php
- classes/OccurrenceIndividual.php
- classes/OccurrenceLabel.php
- classes/OccurrenceManager.php
- classes/OccurrenceSesar.php
- classes/RpcOccurrenceEditor.php
- Activate sort by option within display. Still needs management UI
> Additional Identifier development

- classes/OccurrenceLoans.php
- collections/loans/incoming.php
- collections/loans/outgoing.php
- collections/loans/reports/defaultinvoice.php
- collections/loans/reports/defaultspecimenlist.php
- collections/loans/specimentab.php
- collections/loans/specnoteseditor.php
- Add additional identifiers to spreadsheet html display
- Add additional identifiers csv output
- Improve management tool layout
- Add all identifiers as default search for adding specimens to loan
- Misc bug and layout adjustments
> NEON loan check-in issue

- collections/loans/specimentab.php
- minor adjustments to previous submit
> Loan Management Dev

- api/app/Collection.php
- api/app/Http/Controllers/CollectionController.php
- api/app/Http/Controllers/InstallationController.php
- api/app/Http/Controllers/OccurrenceController.php
- api/routes/web.php
- api/storage/api-docs/api-docs.json
- Add collection element as an API call
- Extend and adjust Swagger documentation and republish swagger output
- Misc adjustments to installation and collection controller
> API Developments

- classes/OccurrenceCollectionProfile.php
- classes/OmCollections.php
- collections/misc/collmetadata.php
- collections/misc/collprofiles.php
- Separate omcollections editing functions into their own class so that they can be used by other tools
- Rework editing functions into mysqli prepared statement calls
> Collection Management dev

- admin/portalindex.php
- classes/OmCollections.php
- classes/PortalIndex.php
- collections/misc/collmetadata.php
- config/schema-1.0/dev/db_schema_patch-dev.sql
- rpc/gettaxon.php
- rpc/taxasuggest.php
- Add ability to import a collection profile as a snapshot and setup adefault import profile
> Portal Index Management development

- classes/OccurrenceEditorManager.php
- Resolve issue where DOES NOT CONTAIN and NOT EQUAL failed to return NULL values
> Occurrence Editor search bug

- admin/portalindex.php
- api/app/Http/Controllers/Controller.php
- classes/PortalIndex.php
- Fine tuning indexing capabilities
> Portal Indexing development

- classes/ImageProcessor.php
- Extend CyVerse processing to so that image links are updated whenever they already exist rather than just skipped
> Image processing dev

- collections/map/index.php
- imagelib/search.php
- index_template.php
- taxa/taxonomy/batchloader.php
- Explicitly define base directory
> Scientific name autocomplete adjustments

- js/symb/collections.editor.main.js
- js/symb/collections.editor.observations.js
- js/symb/collections.editor.tools.js
- Fully deactivate until we can figure out a better option
> Coordinate verification

- config/schema-1.0/dev/db_schema_patch-dev.sql
- Extend dataset table to include citation and GUID data
> Schema changes - dataset table

- classes/OccurrenceEditorManager.php
- collections/editor/occurrenceeditor.php
- js/symb/collections.editor.main.js
- js/symb/collections.editor.query.js
- Avoid saving identifiers multiple times if editor is refreshed
- Fix bug that was interfering with verification and notification of unsaved data
> Occurrence editor modifications

- classes/DwcArchiverCore.php
- classes/OccurrenceDownload.php
- classes/OccurrenceEditorManager.php
- collections/download/downloadhandler.php
- collections/specprocessor/exporter.php
- config/schema-1.0/dev/db_schema_patch-dev.sql
- Integrate additional identifiers (omoccuridentifiers) into DwC-Archive export tools
- Adjustments and bug fix to occurrence editor filtering tool
- Add unique key to omoccuridentifiers table
> Occurrence Download developments

- classes/OccurrenceEditReview.php
- Remove row count call so that MYSQLI_USE_RESULT setting could export complete recordsets
> Occurrence Editor review export adjustment

- classes/OccurrenceCollectionProfile.php
- When updating publishingOrganizationKey within dataset, submit full dataset data object with only the publishingOrganizationKey modified
> GBIF Publishing development

- classes/OccurrenceLoans.php
- collections/loans/outgoing.php
- collections/loans/rpc/insertLoanSpecimens.php
- collections/loans/specimentab.php
- Fixed bug interfering with linking a specimen to a loan via scanning a barcode
- Misc workflow adjustments
> Occurrence Loan bug

- classes/OccurrenceSesar.php
- Rework function used to connect to SESAR API
- Improved error catching
> SESAR IGSN management tool dev

- classes/OccurrenceSesar.php
- Modification to allow single function to be used to return data from new and old SESAR API end points
> SESAR IGSN dev

- classes/DwcArchiverCore.php
- collections/download/downloadhandler.php
- Bug fix that interfered with download of records with coordinates
> GeoLocate CoGe download bug

- classes/DwcArchiverCore.php
- classes/DwcArchiverOccurrence.php
- Exclude some tasks that are not needed for Geolocate to speed up data packaging and exclude unnecessary data
> GeoLocate CoGe Module dev

- classes/DwcArchiverCore.php
- collections/specprocessor/rpc/coge_build_dwca.php
- Adjust AJAX handler to new filter criteria that allows for georeferenced data to be pushed to GeoLocate
> GeoLocate CoGe download dev

- classes/DwcArchiverCore.php
- collections/specprocessor/geolocate.php
- collections/specprocessor/rpc/coge_build_dwca.php
- js/symb/geolocate.js
- Improved error reporting
- Bug fix that was downloading a local copy of the data whenever any button was pushed
- Fix bug that was interfering with publishing datasets with coordinates
> GeoLocate CoGe Dev and Debugging

- api/app/Http/Controllers/OccurrenceAnnotationController.php
- api/app/Http/Controllers/OccurrenceController.php
- api/app/Http/Controllers/TaxonomyDescriptionController.php
- api/routes/web.php
- api/storage/api-docs/api-docs.json
- config/schema-1.0/dev/db_schema_patch-dev.sql
- Add Swagger documentation for inventories
- Adjustments to occurrence documentation
- Add inventory package access (e.g. taxa, image URLs, descriptions, etc)
- Misc bugs
> API Documentation update

- classes/DwcArchiverCore.php
- classes/OccurrenceAccessStats.php
- classes/OccurrenceDownload.php
- content/collections/statistics/.gitignore
- Fix bug that was over-recording a download event
> Occurrence Summary

- classes/TaxonomyUpload.php
- taxa/taxonomy/batchloader.php
- Verify map failed to preserve some of the selected field mapping
- Remove imbedded taxon rank from unnitname3 input variable
> Taxonomy Upload debugging

- classes/TaxonomyEditorManager.php
- Minor fix that ensures that kingdomName is populated when a new taxon is added to the thesaurus
> Taxonomy Loading bug

- classes/ImageCleaner.php
- classes/ImageShared.php
- classes/OccurrenceEditorImages.php
- imagelib/admin/thumbnailbuilder.php
- Suppress SSL cert verification when checking image DIM
- Reduce number of times image DIMs are checked when building thumbnails
- Improve error reporting when building thumbnails
> Thumbnail Management

- classes/DwcArchiverCore.php
- classes/DwcArchiverPublisher.php
- collections/datasets/datapublisher.php
- Fix issue that was causing batch DwC-A publisher to publish same dataset over and over again
- Improvement on input variable sanitation
> DwC-A bug fix

- collections/editor/includes/geotools.php
- collections/editor/observationsubmit.php
- collections/editor/occurrenceeditor.php
- collections/editor/tools/coordformatter.php
- js/symb/collections.editor.main.js
- js/symb/collections.georef.batchgeoreftool.js
- js/symb/collections.georef.js
- UTM from southern hemisphere failed to covert correctly due to need to preadjust UTM northing
> UTM to LatLng conversion bug

- classes/DwcArchiverOccurrence.php
-Integrate herbarium specimen duplicate relationships into associatedOccurrence output
> DwC-Archive development

- classes/DwcArchiverCore.php
- Custom downloads only applied single conditions
> Occurrence Custom Download bug

- classes/MediaResolutionTools.php
- Ad code to dynamically determine local path to media file
> Media Remapping tool dev

- classes/MediaResolutionTools.php
> Media Migration tool adjustment

- classes/MediaResolutionTools.php
> Media Migration tool

- config/schema-1.0/dev/db_schema_patch-dev.sql
- Maintain source identifier within determination table
> Minor DB Schema Adjustment

- classes/ImageLibraryBrowser.php
- classes/Manager.php
- classes/OccurrenceProtectedSpecies.php
- classes/OccurrenceTaxaManager.php
- collections/misc/protectedspecies.php
- imagelib/index.php
- taxa/index.php
- Variable sanitation and other security patch issues
> hotfix 2023-08-31 (#611)

- checklists/checklist.php
- classes/DwcArchiverBaseManager.php
- classes/DwcArchiverCore.php
- classes/OccurrenceEditorDeterminations.php
- collections/list.php
- config/symbbase.php
- js/symb/collections.list.js
- taxa/taxonomy/taxoneditor.php
- DWC-A publushing  -- Close and destroy file handlers and class instances, thus ensuring full output of buffers. Integrates [Dev bug fix #1223](https://github.com/BioKIC/Symbiota/pull/1233) into master.  
- Occurrence Search:  -- URL encode search variables to ensure "copy link" function and map links work when spaces or special characters are included within terms. Addresses issue: https://github.com/BioKIC/Symbiota/issues/1212
- Occurrence Editor:  -- Ensure that image tids are updated to make occurrence identifications. Integrates [Dev bug fix #1239](https://github.com/BioKIC/Symbiota/pull/1239) into master.
> Hotfix 2024 04 29 (#1254)

- classes/ChecklistVoucherManager.php
- classes/ImageLocalProcessor.php
- classes/OccurrenceMapManager.php
- config/symbbase.php
* Hotfix 2024-05-22
- Checklist management: -- Adjust taxon merge function to accommodate PHP v8.1 fatal exceptions during foreign key conflicts within SQL update statements, which previously simply returned false value with a warning
- Image processing: -- Bug resolution to avoid fatal error where an array function is incorrectly used on a string. Resolves issue https://github.com/BioKIC/Symbiota/issues/1366
- Occurrence Mapping: -- Fix bug interfering with the exclusion of protected occurrences within the mapping tools when user is not approved to view these records. Associated with issue: https://github.com/BioKIC/Symbiota/issues/1375
Thanks for contributing and keeping it clean!
> Hotfix 2024 05 22 (#1374)

- checklists/index.php
- classes/ChecklistManager.php
- classes/DwcArchiverPublisher.php
- config/symbbase.php
- ident/index.php
- Inventory and Project Management  -- Display all checklists that have at least one linked taxon OR is a parent checklist inheriting taxa from a child checklist ([Issue #1532](https://github.com/BioKIC/Symbiota/issues/1532)) -- Removed limit that required checklist to have at least 10 linked taxa -- Order checklists by project and checklists names -- Only display Global symbol within map display option when one or more checklists within a group have lat/long centroids -- Make project title an active link that opens the project within the project details page
- DwC-A Publishing  -- Fix fatal error when DwC-A path fails to return a data file
Thanks for contributing and keeping it clean!
> Hotfix 2024 07 25 (#1591)

- classes/OccurrenceEditorManager.php
- config/symbbase.php
- Minor bug fix that was interfering with saving of locationRemarks when a new record is saved (resolves https://github.com/BioKIC/Symbiota/issues/1445)
> Hotfix 2024 08 22 (#1677)

- config/symbbase.php
- css/symbiota/header.css
- css/symbiota/main.css
- includes/header_template.php
* Switch header buttons to use HTML button element for better UX
* Adjust styling to restoring honoring header button text color
* Improve header button layout on <768px display
> Header render Fixes (#1962)
